/*
 * This file is generated by jOOQ.
 */
package com.salescode.jooq;


import com.fasterxml.jackson.databind.JsonNode;
import com.salescode.channelkart.converters.ActiveStatus;


import com.salescode.jooq.generated.tables.pojos.CkHierarchyMetadata;
import com.salescode.jooq.generated.tables.pojos.CkOutletDetails;
import com.salescode.jooq.generated.tables.pojos.CkUser;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.jooq.DSLContext;
import org.jooq.JSON;

import static com.salescode.jooq.generated.tables.CkHierarchyMetadata.CK_HIERARCHY_METADATA;
import static com.salescode.jooq.generated.tables.CkOutletDetails.CK_OUTLET_DETAILS;
import static com.salescode.jooq.generated.tables.CkOutletDetailsHierarchymetadata.CK_OUTLET_DETAILS_HIERARCHYMETADATA;
import static com.salescode.jooq.generated.tables.CkUser.CK_USER;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CkOutletDetailsWrapper {

    private static final long serialVersionUID = 1L;


    private String id;
    private ActiveStatus activeStatus;
    private String activeStatusReason;
    private String createdBy;
    private Date creationTime;
    private JsonNode extendedAttributes;
    private Date lastModifiedTime;
    private String lob;
    private String modifiedBy;
    private String source;
    private Integer version;
    private String account;
    private String address;
    private String beat;
    private String beatName;
    private String channel;
    private String contactName;
    private String contactno;
    private String displayAddress;
    private String frequency;
    private String gstNo;
    private Date lastOrderDate;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private Boolean mapped;
    private String marketId;
    private String marketName;
    private String outletCategory;
    private String outletClass;
    private String outletcode;
    private String outletName;
    private String outletType;
    private String tinNo;
    private String locationHierarchy;
    private String loginid;
    private JSON accessibleby;
    private JSON accessibleBy;
    private String hash;
    private Object coordinate;
    private Date doo;
    private String dtype;
    private String hierarchy;
    private Byte changed;
    private String distributionChannel;
    private String outletDivision;
    private String soldTo;
    private String subChannel;
    private String subTerritory;
    private String blobKey;
    private String email;
    private String controlGroup;
    private String normalizedHierarchy;
    private String priceListId;
    private CkUser userName;
    private List<CkHierarchyMetadata> immediateParent;


    public CkOutletDetailsWrapper() {}

    public CkOutletDetailsWrapper(CkOutletDetails value, DSLContext dsl) {
        this.id = value.getId();
        this.activeStatus = value.getActiveStatus();
        this.activeStatusReason = value.getActiveStatusReason();
        this.createdBy = value.getCreatedBy();
        this.creationTime = value.getCreationTime();
        this.extendedAttributes = value.getExtendedAttributes();
        this.lastModifiedTime = value.getLastModifiedTime();
        this.lob = value.getLob();
        this.modifiedBy = value.getModifiedBy();
        this.source = value.getSource();
        this.version = value.getVersion();
        this.account = value.getAccount();
        this.address = value.getAddress();
        this.beat = value.getBeat();
        this.beatName = value.getBeatName();
        this.channel = value.getChannel();
        this.contactName = value.getContactName();
        this.contactno = value.getContactno();
        this.displayAddress = value.getDisplayAddress();
        this.frequency = value.getFrequency();
        this.gstNo = value.getGstNo();
        this.lastOrderDate = value.getLastOrderDate();
        this.latitude = value.getLatitude();
        this.longitude = value.getLongitude();
        this.mapped = value.getMapped();
        this.marketId = value.getMarketId();
        this.marketName = value.getMarketName();
        this.outletCategory = value.getOutletCategory();
        this.outletClass = value.getOutletClass();
        this.outletcode = value.getOutletcode();
        this.outletName = value.getOutletName();
        this.outletType = value.getOutletType();
        this.tinNo = value.getTinNo();
        this.locationHierarchy = value.getLocationHierarchy();
        this.loginid = value.getLoginid();
        this.accessibleby = value.getAccessibleby();
        this.accessibleBy = value.getAccessibleBy();
        this.hash = value.getHash();
        this.coordinate = value.getCoordinate();
        this.doo = value.getDoo();
        this.dtype = value.getDtype();
        this.hierarchy = value.getHierarchy();
        this.changed = value.getChanged();
        this.distributionChannel = value.getDistributionChannel();
        this.outletDivision = value.getOutletDivision();
        this.soldTo = value.getSoldTo();
        this.subChannel = value.getSubChannel();
        this.subTerritory = value.getSubTerritory();
        this.blobKey = value.getBlobKey();
        this.email = value.getEmail();
        this.controlGroup = value.getControlGroup();
        this.normalizedHierarchy = value.getNormalizedHierarchy();
        this.priceListId = value.getPriceListId();
        this.userName = dsl.select(CK_OUTLET_DETAILS.fields())
                .from(CK_OUTLET_DETAILS)
                .join(CK_USER)
                .on(CK_OUTLET_DETAILS.LOGINID.eq(CK_USER.LOGINID))
                .fetchOneInto(CkUser.class);

        this.immediateParent = dsl.select(CK_HIERARCHY_METADATA.fields())  // Select fields from the HierarchyMetaData table
                .from(CK_OUTLET_DETAILS)
                .join(CK_OUTLET_DETAILS_HIERARCHYMETADATA)
                .on(CK_OUTLET_DETAILS.ID.eq(CK_OUTLET_DETAILS_HIERARCHYMETADATA.OUTLET_ID))  // Join on outlet_id
                .join(CK_HIERARCHY_METADATA)
                .on(CK_OUTLET_DETAILS_HIERARCHYMETADATA.HIERARCHY_METADATA_ID.eq(CK_HIERARCHY_METADATA.ID))  // Join on hierarchy_metadata_id
                .where(CK_OUTLET_DETAILS.ID.eq(value.getId()))  // Filter by outlet_id
                .fetchInto(CkHierarchyMetadata.class);
    }

    public CkOutletDetailsWrapper(
            String id,
            ActiveStatus activeStatus,
            String activeStatusReason,
            String createdBy,
            Date creationTime,
            JsonNode extendedAttributes,
            Date lastModifiedTime,
            String lob,
            String modifiedBy,
            String source,
            Integer version,
            String account,
            String address,
            String beat,
            String beatName,
            String channel,
            String contactName,
            String contactno,
            String displayAddress,
            String frequency,
            String gstNo,
            Date lastOrderDate,
            BigDecimal latitude,
            BigDecimal longitude,
            Boolean mapped,
            String marketId,
            String marketName,
            String outletCategory,
            String outletClass,
            String outletcode,
            String outletName,
            String outletType,
            String tinNo,
            String locationHierarchy,
            String loginid,
            JSON accessibleby,
            JSON accessibleBy,
            String hash,
            Object coordinate,
            Date doo,
            String dtype,
            String hierarchy,
            Byte changed,
            String distributionChannel,
            String outletDivision,
            String soldTo,
            String subChannel,
            String subTerritory,
            String blobKey,
            String email,
            String controlGroup,
            String normalizedHierarchy,
            String priceListId,
            CkUser userName,
            List<CkHierarchyMetadata> immediateParent
    ) {
        this.id = id;
        this.activeStatus = activeStatus;
        this.activeStatusReason = activeStatusReason;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.extendedAttributes = extendedAttributes;
        this.lastModifiedTime = lastModifiedTime;
        this.lob = lob;
        this.modifiedBy = modifiedBy;
        this.source = source;
        this.version = version;
        this.account = account;
        this.address = address;
        this.beat = beat;
        this.beatName = beatName;
        this.channel = channel;
        this.contactName = contactName;
        this.contactno = contactno;
        this.displayAddress = displayAddress;
        this.frequency = frequency;
        this.gstNo = gstNo;
        this.lastOrderDate = lastOrderDate;
        this.latitude = latitude;
        this.longitude = longitude;
        this.mapped = mapped;
        this.marketId = marketId;
        this.marketName = marketName;
        this.outletCategory = outletCategory;
        this.outletClass = outletClass;
        this.outletcode = outletcode;
        this.outletName = outletName;
        this.outletType = outletType;
        this.tinNo = tinNo;
        this.locationHierarchy = locationHierarchy;
        this.loginid = loginid;
        this.accessibleby = accessibleby;
        this.accessibleBy = accessibleBy;
        this.hash = hash;
        this.coordinate = coordinate;
        this.doo = doo;
        this.dtype = dtype;
        this.hierarchy = hierarchy;
        this.changed = changed;
        this.distributionChannel = distributionChannel;
        this.outletDivision = outletDivision;
        this.soldTo = soldTo;
        this.subChannel = subChannel;
        this.subTerritory = subTerritory;
        this.blobKey = blobKey;
        this.email = email;
        this.controlGroup = controlGroup;
        this.normalizedHierarchy = normalizedHierarchy;
        this.priceListId = priceListId;
        this.userName = userName;
        this.immediateParent = immediateParent;
    }

    /**
     * Getter for <code>ck_outlet_details.id</code>.
     */
    
    
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>ck_outlet_details.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>ck_outlet_details.active_status</code>.
     */
    public ActiveStatus getActiveStatus() {
        return this.activeStatus;
    }

    /**
     * Setter for <code>ck_outlet_details.active_status</code>.
     */
    public void setActiveStatus(ActiveStatus activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * Getter for <code>ck_outlet_details.active_status_reason</code>.
     */
    
    public String getActiveStatusReason() {
        return this.activeStatusReason;
    }

    /**
     * Setter for <code>ck_outlet_details.active_status_reason</code>.
     */
    public void setActiveStatusReason(String activeStatusReason) {
        this.activeStatusReason = activeStatusReason;
    }

    /**
     * Getter for <code>ck_outlet_details.created_by</code>.
     */
    
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>ck_outlet_details.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>ck_outlet_details.creation_time</code>.
     */
    public Date getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>ck_outlet_details.creation_time</code>.
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>ck_outlet_details.extended_attributes</code>.
     */
    public JsonNode getExtendedAttributes() {
        return this.extendedAttributes;
    }

    /**
     * Setter for <code>ck_outlet_details.extended_attributes</code>.
     */
    public void setExtendedAttributes(JsonNode extendedAttributes) {
        this.extendedAttributes = extendedAttributes;
    }

    /**
     * Getter for <code>ck_outlet_details.last_modified_time</code>.
     */
    public Date getLastModifiedTime() {
        return this.lastModifiedTime;
    }

    /**
     * Setter for <code>ck_outlet_details.last_modified_time</code>.
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * Getter for <code>ck_outlet_details.lob</code>.
     */
    
    public String getLob() {
        return this.lob;
    }

    /**
     * Setter for <code>ck_outlet_details.lob</code>.
     */
    public void setLob(String lob) {
        this.lob = lob;
    }

    /**
     * Getter for <code>ck_outlet_details.modified_by</code>.
     */
    
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>ck_outlet_details.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>ck_outlet_details.source</code>.
     */
    
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>ck_outlet_details.source</code>.
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Getter for <code>ck_outlet_details.version</code>.
     */
    
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>ck_outlet_details.version</code>.
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for <code>ck_outlet_details.account</code>.
     */
    
    public String getAccount() {
        return this.account;
    }

    /**
     * Setter for <code>ck_outlet_details.account</code>.
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * Getter for <code>ck_outlet_details.address</code>.
     */
    
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>ck_outlet_details.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>ck_outlet_details.beat</code>.
     */
    
    public String getBeat() {
        return this.beat;
    }

    /**
     * Setter for <code>ck_outlet_details.beat</code>.
     */
    public void setBeat(String beat) {
        this.beat = beat;
    }

    /**
     * Getter for <code>ck_outlet_details.beat_name</code>.
     */
    
    public String getBeatName() {
        return this.beatName;
    }

    /**
     * Setter for <code>ck_outlet_details.beat_name</code>.
     */
    public void setBeatName(String beatName) {
        this.beatName = beatName;
    }

    /**
     * Getter for <code>ck_outlet_details.channel</code>.
     */
    
    public String getChannel() {
        return this.channel;
    }

    /**
     * Setter for <code>ck_outlet_details.channel</code>.
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * Getter for <code>ck_outlet_details.contact_name</code>.
     */
    
    public String getContactName() {
        return this.contactName;
    }

    /**
     * Setter for <code>ck_outlet_details.contact_name</code>.
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * Getter for <code>ck_outlet_details.contactno</code>.
     */
    
    public String getContactno() {
        return this.contactno;
    }

    /**
     * Setter for <code>ck_outlet_details.contactno</code>.
     */
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    /**
     * Getter for <code>ck_outlet_details.display_address</code>.
     */
    
    public String getDisplayAddress() {
        return this.displayAddress;
    }

    /**
     * Setter for <code>ck_outlet_details.display_address</code>.
     */
    public void setDisplayAddress(String displayAddress) {
        this.displayAddress = displayAddress;
    }

    /**
     * Getter for <code>ck_outlet_details.frequency</code>.
     */
    
    public String getFrequency() {
        return this.frequency;
    }

    /**
     * Setter for <code>ck_outlet_details.frequency</code>.
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    /**
     * Getter for <code>ck_outlet_details.gst_no</code>.
     */
    
    public String getGstNo() {
        return this.gstNo;
    }

    /**
     * Setter for <code>ck_outlet_details.gst_no</code>.
     */
    public void setGstNo(String gstNo) {
        this.gstNo = gstNo;
    }

    /**
     * Getter for <code>ck_outlet_details.last_order_date</code>.
     */
    public Date getLastOrderDate() {
        return this.lastOrderDate;
    }

    /**
     * Setter for <code>ck_outlet_details.last_order_date</code>.
     */
    public void setLastOrderDate(Date lastOrderDate) {
        this.lastOrderDate = lastOrderDate;
    }

    /**
     * Getter for <code>ck_outlet_details.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>ck_outlet_details.latitude</code>.
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>ck_outlet_details.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>ck_outlet_details.longitude</code>.
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for <code>ck_outlet_details.mapped</code>.
     */
    
    public Boolean getMapped() {
        return this.mapped;
    }

    /**
     * Setter for <code>ck_outlet_details.mapped</code>.
     */
    public void setMapped(Boolean mapped) {
        this.mapped = mapped;
    }

    /**
     * Getter for <code>ck_outlet_details.market_id</code>.
     */
    
    public String getMarketId() {
        return this.marketId;
    }

    /**
     * Setter for <code>ck_outlet_details.market_id</code>.
     */
    public void setMarketId(String marketId) {
        this.marketId = marketId;
    }

    /**
     * Getter for <code>ck_outlet_details.market_name</code>.
     */
    
    public String getMarketName() {
        return this.marketName;
    }

    /**
     * Setter for <code>ck_outlet_details.market_name</code>.
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName;
    }

    /**
     * Getter for <code>ck_outlet_details.outlet_category</code>.
     */
    
    public String getOutletCategory() {
        return this.outletCategory;
    }

    /**
     * Setter for <code>ck_outlet_details.outlet_category</code>.
     */
    public void setOutletCategory(String outletCategory) {
        this.outletCategory = outletCategory;
    }

    /**
     * Getter for <code>ck_outlet_details.outlet_class</code>.
     */
    
    public String getOutletClass() {
        return this.outletClass;
    }

    /**
     * Setter for <code>ck_outlet_details.outlet_class</code>.
     */
    public void setOutletClass(String outletClass) {
        this.outletClass = outletClass;
    }

    /**
     * Getter for <code>ck_outlet_details.outletcode</code>.
     */
    
    
    public String getOutletcode() {
        return this.outletcode;
    }

    /**
     * Setter for <code>ck_outlet_details.outletcode</code>.
     */
    public void setOutletcode(String outletcode) {
        this.outletcode = outletcode;
    }

    /**
     * Getter for <code>ck_outlet_details.outlet_name</code>.
     */
    
    public String getOutletName() {
        return this.outletName;
    }

    /**
     * Setter for <code>ck_outlet_details.outlet_name</code>.
     */
    public void setOutletName(String outletName) {
        this.outletName = outletName;
    }

    /**
     * Getter for <code>ck_outlet_details.outlet_type</code>.
     */
    
    public String getOutletType() {
        return this.outletType;
    }

    /**
     * Setter for <code>ck_outlet_details.outlet_type</code>.
     */
    public void setOutletType(String outletType) {
        this.outletType = outletType;
    }

    /**
     * Getter for <code>ck_outlet_details.tin_no</code>.
     */
    
    public String getTinNo() {
        return this.tinNo;
    }

    /**
     * Setter for <code>ck_outlet_details.tin_no</code>.
     */
    public void setTinNo(String tinNo) {
        this.tinNo = tinNo;
    }

    /**
     * Getter for <code>ck_outlet_details.location_hierarchy</code>.
     */
    
    public String getLocationHierarchy() {

        return this.locationHierarchy;
    }

    /**
     * Setter for <code>ck_outlet_details.location_hierarchy</code>.
     */
    public void setLocationHierarchy(String locationHierarchy) {
        this.locationHierarchy = locationHierarchy;
    }

    /**
     * Getter for <code>ck_outlet_details.loginid</code>.
     */
    
    public String getLoginid() {
        return this.loginid;
    }

    /**
     * Setter for <code>ck_outlet_details.loginid</code>.
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }

    /**
     * Getter for <code>ck_outlet_details.accessibleBy</code>.
     */
    public JSON getAccessibleby() {
        return this.accessibleby;
    }

    /**
     * Setter for <code>ck_outlet_details.accessibleBy</code>.
     */
    public void setAccessibleby(JSON accessibleby) {
        this.accessibleby = accessibleby;
    }

    /**
     * Getter for <code>ck_outlet_details.accessible_by</code>.
     */
    public JSON getAccessibleBy() {
        return this.accessibleBy;
    }

    /**
     * Setter for <code>ck_outlet_details.accessible_by</code>.
     */
    public void setAccessibleBy(JSON accessibleBy) {
        this.accessibleBy = accessibleBy;
    }

    /**
     * Getter for <code>ck_outlet_details.hash</code>.
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>ck_outlet_details.hash</code>.
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getCoordinate() {
        return this.coordinate;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setCoordinate(Object coordinate) {
        this.coordinate = coordinate;
    }

    /**
     * Getter for <code>ck_outlet_details.doo</code>.
     */
    public Date getDoo() {
        return this.doo;
    }

    /**
     * Setter for <code>ck_outlet_details.doo</code>.
     */
    public void setDoo(Date doo) {
        this.doo = doo;
    }

    /**
     * Getter for <code>ck_outlet_details.dtype</code>.
     */
    
    
    public String getDtype() {
        return this.dtype;
    }

    /**
     * Setter for <code>ck_outlet_details.dtype</code>.
     */
    public void setDtype(String dtype) {
        this.dtype = dtype;
    }

    /**
     * Getter for <code>ck_outlet_details.hierarchy</code>.
     */
    public String getHierarchy() {
        return this.hierarchy;
    }

    /**
     * Setter for <code>ck_outlet_details.hierarchy</code>.
     */
    public void setHierarchy(String hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for <code>ck_outlet_details.changed</code>.
     */
    public Byte getChanged() {
        return this.changed;
    }

    /**
     * Setter for <code>ck_outlet_details.changed</code>.
     */
    public void setChanged(Byte changed) {
        this.changed = changed;
    }

    /**
     * Getter for <code>ck_outlet_details.distribution_channel</code>.
     */
    
    public String getDistributionChannel() {
        return this.distributionChannel;
    }

    /**
     * Setter for <code>ck_outlet_details.distribution_channel</code>.
     */
    public void setDistributionChannel(String distributionChannel) {
        this.distributionChannel = distributionChannel;
    }

    /**
     * Getter for <code>ck_outlet_details.outlet_division</code>.
     */
    
    public String getOutletDivision() {
        return this.outletDivision;
    }

    /**
     * Setter for <code>ck_outlet_details.outlet_division</code>.
     */
    public void setOutletDivision(String outletDivision) {
        this.outletDivision = outletDivision;
    }

    /**
     * Getter for <code>ck_outlet_details.sold_to</code>.
     */
    
    public String getSoldTo() {
        return this.soldTo;
    }

    /**
     * Setter for <code>ck_outlet_details.sold_to</code>.
     */
    public void setSoldTo(String soldTo) {
        this.soldTo = soldTo;
    }

    /**
     * Getter for <code>ck_outlet_details.sub_channel</code>.
     */
    
    public String getSubChannel() {
        return this.subChannel;
    }

    /**
     * Setter for <code>ck_outlet_details.sub_channel</code>.
     */
    public void setSubChannel(String subChannel) {
        this.subChannel = subChannel;
    }

    /**
     * Getter for <code>ck_outlet_details.sub_territory</code>.
     */
    
    public String getSubTerritory() {
        return this.subTerritory;
    }

    /**
     * Setter for <code>ck_outlet_details.sub_territory</code>.
     */
    public void setSubTerritory(String subTerritory) {
        this.subTerritory = subTerritory;
    }

    /**
     * Getter for <code>ck_outlet_details.blob_key</code>.
     */
    
    public String getBlobKey() {
        return this.blobKey;
    }

    /**
     * Setter for <code>ck_outlet_details.blob_key</code>.
     */
    public void setBlobKey(String blobKey) {
        this.blobKey = blobKey;
    }

    /**
     * Getter for <code>ck_outlet_details.email</code>.
     */
    
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>ck_outlet_details.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>ck_outlet_details.control_group</code>.
     */
    
    public String getControlGroup() {
        return this.controlGroup;
    }

    /**
     * Setter for <code>ck_outlet_details.control_group</code>.
     */
    public void setControlGroup(String controlGroup) {
        this.controlGroup = controlGroup;
    }

    /**
     * Getter for <code>ck_outlet_details.normalized_hierarchy</code>.
     */
    public String getNormalizedHierarchy() {
        return this.normalizedHierarchy;
    }

    /**
     * Setter for <code>ck_outlet_details.normalized_hierarchy</code>.
     */
    public void setNormalizedHierarchy(String normalizedHierarchy) {
        this.normalizedHierarchy = normalizedHierarchy;
    }

    /**
     * Getter for <code>ck_outlet_details.price_list_id</code>.
     */
    
    public String getPriceListId() {
        return this.priceListId;
    }

    /**
     * Setter for <code>ck_outlet_details.price_list_id</code>.
     */
    public void setPriceListId(String priceListId) {
        this.priceListId = priceListId;
    }

//    @Override
//    public boolean equals(Object obj) {
//        if (this == obj)
//            return true;
//        if (obj == null)
//            return false;
//        if (getClass() != obj.getClass())
//            return false;
//        final CkOutletDetails other = (CkOutletDetails) obj;
//        if (this.id == null) {
//            if (other.id != null)
//                return false;
//        }
//        else if (!this.id.equals(other.id))
//            return false;
//        if (this.activeStatus == null) {
//            if (other.activeStatus != null)
//                return false;
//        }
//        else if (!this.activeStatus.equals(other.activeStatus))
//            return false;
//        if (this.activeStatusReason == null) {
//            if (other.activeStatusReason != null)
//                return false;
//        }
//        else if (!this.activeStatusReason.equals(other.activeStatusReason))
//            return false;
//        if (this.createdBy == null) {
//            if (other.createdBy != null)
//                return false;
//        }
//        else if (!this.createdBy.equals(other.createdBy))
//            return false;
//        if (this.creationTime == null) {
//            if (other.creationTime != null)
//                return false;
//        }
//        else if (!this.creationTime.equals(other.creationTime))
//            return false;
//        if (this.extendedAttributes == null) {
//            if (other.extendedAttributes != null)
//                return false;
//        }
//        else if (!this.extendedAttributes.equals(other.extendedAttributes))
//            return false;
//        if (this.lastModifiedTime == null) {
//            if (other.lastModifiedTime != null)
//                return false;
//        }
//        else if (!this.lastModifiedTime.equals(other.lastModifiedTime))
//            return false;
//        if (this.lob == null) {
//            if (other.lob != null)
//                return false;
//        }
//        else if (!this.lob.equals(other.lob))
//            return false;
//        if (this.modifiedBy == null) {
//            if (other.modifiedBy != null)
//                return false;
//        }
//        else if (!this.modifiedBy.equals(other.modifiedBy))
//            return false;
//        if (this.source == null) {
//            if (other.source != null)
//                return false;
//        }
//        else if (!this.source.equals(other.source))
//            return false;
//        if (this.version == null) {
//            if (other.version != null)
//                return false;
//        }
//        else if (!this.version.equals(other.version))
//            return false;
//        if (this.account == null) {
//            if (other.account != null)
//                return false;
//        }
//        else if (!this.account.equals(other.account))
//            return false;
//        if (this.address == null) {
//            if (other.address != null)
//                return false;
//        }
//        else if (!this.address.equals(other.address))
//            return false;
//        if (this.beat == null) {
//            if (other.beat != null)
//                return false;
//        }
//        else if (!this.beat.equals(other.beat))
//            return false;
//        if (this.beatName == null) {
//            if (other.beatName != null)
//                return false;
//        }
//        else if (!this.beatName.equals(other.beatName))
//            return false;
//        if (this.channel == null) {
//            if (other.channel != null)
//                return false;
//        }
//        else if (!this.channel.equals(other.channel))
//            return false;
//        if (this.contactName == null) {
//            if (other.contactName != null)
//                return false;
//        }
//        else if (!this.contactName.equals(other.contactName))
//            return false;
//        if (this.contactno == null) {
//            if (other.contactno != null)
//                return false;
//        }
//        else if (!this.contactno.equals(other.contactno))
//            return false;
//        if (this.displayAddress == null) {
//            if (other.displayAddress != null)
//                return false;
//        }
//        else if (!this.displayAddress.equals(other.displayAddress))
//            return false;
//        if (this.frequency == null) {
//            if (other.frequency != null)
//                return false;
//        }
//        else if (!this.frequency.equals(other.frequency))
//            return false;
//        if (this.gstNo == null) {
//            if (other.gstNo != null)
//                return false;
//        }
//        else if (!this.gstNo.equals(other.gstNo))
//            return false;
//        if (this.lastOrderDate == null) {
//            if (other.lastOrderDate != null)
//                return false;
//        }
//        else if (!this.lastOrderDate.equals(other.lastOrderDate))
//            return false;
//        if (this.latitude == null) {
//            if (other.latitude != null)
//                return false;
//        }
//        else if (!this.latitude.equals(other.latitude))
//            return false;
//        if (this.longitude == null) {
//            if (other.longitude != null)
//                return false;
//        }
//        else if (!this.longitude.equals(other.longitude))
//            return false;
//        if (this.mapped == null) {
//            if (other.mapped != null)
//                return false;
//        }
//        else if (!this.mapped.equals(other.mapped))
//            return false;
//        if (this.marketId == null) {
//            if (other.marketId != null)
//                return false;
//        }
//        else if (!this.marketId.equals(other.marketId))
//            return false;
//        if (this.marketName == null) {
//            if (other.marketName != null)
//                return false;
//        }
//        else if (!this.marketName.equals(other.marketName))
//            return false;
//        if (this.outletCategory == null) {
//            if (other.outletCategory != null)
//                return false;
//        }
//        else if (!this.outletCategory.equals(other.outletCategory))
//            return false;
//        if (this.outletClass == null) {
//            if (other.outletClass != null)
//                return false;
//        }
//        else if (!this.outletClass.equals(other.outletClass))
//            return false;
//        if (this.outletcode == null) {
//            if (other.outletcode != null)
//                return false;
//        }
//        else if (!this.outletcode.equals(other.outletcode))
//            return false;
//        if (this.outletName == null) {
//            if (other.outletName != null)
//                return false;
//        }
//        else if (!this.outletName.equals(other.outletName))
//            return false;
//        if (this.outletType == null) {
//            if (other.outletType != null)
//                return false;
//        }
//        else if (!this.outletType.equals(other.outletType))
//            return false;
//        if (this.tinNo == null) {
//            if (other.tinNo != null)
//                return false;
//        }
//        else if (!this.tinNo.equals(other.tinNo))
//            return false;
//        if (this.locationHierarchy == null) {
//            if (other.locationHierarchy != null)
//                return false;
//        }
//        else if (!this.locationHierarchy.equals(other.locationHierarchy))
//            return false;
//        if (this.loginid == null) {
//            if (other.loginid != null)
//                return false;
//        }
//        else if (!this.loginid.equals(other.loginid))
//            return false;
//        if (this.accessibleby == null) {
//            if (other.accessibleby != null)
//                return false;
//        }
//        else if (!this.accessibleby.equals(other.accessibleby))
//            return false;
//        if (this.accessibleBy == null) {
//            if (other.accessibleBy != null)
//                return false;
//        }
//        else if (!this.accessibleBy.equals(other.accessibleBy))
//            return false;
//        if (this.hash == null) {
//            if (other.hash != null)
//                return false;
//        }
//        else if (!this.hash.equals(other.hash))
//            return false;
//        if (this.coordinate == null) {
//            if (other.coordinate != null)
//                return false;
//        }
//        else if (!this.coordinate.equals(other.coordinate))
//            return false;
//        if (this.doo == null) {
//            if (other.doo != null)
//                return false;
//        }
//        else if (!this.doo.equals(other.doo))
//            return false;
//        if (this.dtype == null) {
//            if (other.dtype != null)
//                return false;
//        }
//        else if (!this.dtype.equals(other.dtype))
//            return false;
//        if (this.hierarchy == null) {
//            if (other.hierarchy != null)
//                return false;
//        }
//        else if (!this.hierarchy.equals(other.hierarchy))
//            return false;
//        if (this.changed == null) {
//            if (other.changed != null)
//                return false;
//        }
//        else if (!this.changed.equals(other.changed))
//            return false;
//        if (this.distributionChannel == null) {
//            if (other.distributionChannel != null)
//                return false;
//        }
//        else if (!this.distributionChannel.equals(other.distributionChannel))
//            return false;
//        if (this.outletDivision == null) {
//            if (other.outletDivision != null)
//                return false;
//        }
//        else if (!this.outletDivision.equals(other.outletDivision))
//            return false;
//        if (this.soldTo == null) {
//            if (other.soldTo != null)
//                return false;
//        }
//        else if (!this.soldTo.equals(other.soldTo))
//            return false;
//        if (this.subChannel == null) {
//            if (other.subChannel != null)
//                return false;
//        }
//        else if (!this.subChannel.equals(other.subChannel))
//            return false;
//        if (this.subTerritory == null) {
//            if (other.subTerritory != null)
//                return false;
//        }
//        else if (!this.subTerritory.equals(other.subTerritory))
//            return false;
//        if (this.blobKey == null) {
//            if (other.blobKey != null)
//                return false;
//        }
//        else if (!this.blobKey.equals(other.blobKey))
//            return false;
//        if (this.email == null) {
//            if (other.email != null)
//                return false;
//        }
//        else if (!this.email.equals(other.email))
//            return false;
//        if (this.controlGroup == null) {
//            if (other.controlGroup != null)
//                return false;
//        }
//        else if (!this.controlGroup.equals(other.controlGroup))
//            return false;
//        if (this.normalizedHierarchy == null) {
//            if (other.normalizedHierarchy != null)
//                return false;
//        }
//        else if (!this.normalizedHierarchy.equals(other.normalizedHierarchy))
//            return false;
//        if (this.priceListId == null) {
//            if (other.priceListId != null)
//                return false;
//        }
//        else if (!this.priceListId.equals(other.priceListId))
//            return false;
//        return true;
//    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.activeStatus == null) ? 0 : this.activeStatus.hashCode());
        result = prime * result + ((this.activeStatusReason == null) ? 0 : this.activeStatusReason.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.creationTime == null) ? 0 : this.creationTime.hashCode());
        result = prime * result + ((this.extendedAttributes == null) ? 0 : this.extendedAttributes.hashCode());
        result = prime * result + ((this.lastModifiedTime == null) ? 0 : this.lastModifiedTime.hashCode());
        result = prime * result + ((this.lob == null) ? 0 : this.lob.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.account == null) ? 0 : this.account.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.beat == null) ? 0 : this.beat.hashCode());
        result = prime * result + ((this.beatName == null) ? 0 : this.beatName.hashCode());
        result = prime * result + ((this.channel == null) ? 0 : this.channel.hashCode());
        result = prime * result + ((this.contactName == null) ? 0 : this.contactName.hashCode());
        result = prime * result + ((this.contactno == null) ? 0 : this.contactno.hashCode());
        result = prime * result + ((this.displayAddress == null) ? 0 : this.displayAddress.hashCode());
        result = prime * result + ((this.frequency == null) ? 0 : this.frequency.hashCode());
        result = prime * result + ((this.gstNo == null) ? 0 : this.gstNo.hashCode());
        result = prime * result + ((this.lastOrderDate == null) ? 0 : this.lastOrderDate.hashCode());
        result = prime * result + ((this.latitude == null) ? 0 : this.latitude.hashCode());
        result = prime * result + ((this.longitude == null) ? 0 : this.longitude.hashCode());
        result = prime * result + ((this.mapped == null) ? 0 : this.mapped.hashCode());
        result = prime * result + ((this.marketId == null) ? 0 : this.marketId.hashCode());
        result = prime * result + ((this.marketName == null) ? 0 : this.marketName.hashCode());
        result = prime * result + ((this.outletCategory == null) ? 0 : this.outletCategory.hashCode());
        result = prime * result + ((this.outletClass == null) ? 0 : this.outletClass.hashCode());
        result = prime * result + ((this.outletcode == null) ? 0 : this.outletcode.hashCode());
        result = prime * result + ((this.outletName == null) ? 0 : this.outletName.hashCode());
        result = prime * result + ((this.outletType == null) ? 0 : this.outletType.hashCode());
        result = prime * result + ((this.tinNo == null) ? 0 : this.tinNo.hashCode());
        result = prime * result + ((this.locationHierarchy == null) ? 0 : this.locationHierarchy.hashCode());
        result = prime * result + ((this.loginid == null) ? 0 : this.loginid.hashCode());
        result = prime * result + ((this.accessibleby == null) ? 0 : this.accessibleby.hashCode());
        result = prime * result + ((this.accessibleBy == null) ? 0 : this.accessibleBy.hashCode());
        result = prime * result + ((this.hash == null) ? 0 : this.hash.hashCode());
        result = prime * result + ((this.coordinate == null) ? 0 : this.coordinate.hashCode());
        result = prime * result + ((this.doo == null) ? 0 : this.doo.hashCode());
        result = prime * result + ((this.dtype == null) ? 0 : this.dtype.hashCode());
        result = prime * result + ((this.hierarchy == null) ? 0 : this.hierarchy.hashCode());
        result = prime * result + ((this.changed == null) ? 0 : this.changed.hashCode());
        result = prime * result + ((this.distributionChannel == null) ? 0 : this.distributionChannel.hashCode());
        result = prime * result + ((this.outletDivision == null) ? 0 : this.outletDivision.hashCode());
        result = prime * result + ((this.soldTo == null) ? 0 : this.soldTo.hashCode());
        result = prime * result + ((this.subChannel == null) ? 0 : this.subChannel.hashCode());
        result = prime * result + ((this.subTerritory == null) ? 0 : this.subTerritory.hashCode());
        result = prime * result + ((this.blobKey == null) ? 0 : this.blobKey.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.controlGroup == null) ? 0 : this.controlGroup.hashCode());
        result = prime * result + ((this.normalizedHierarchy == null) ? 0 : this.normalizedHierarchy.hashCode());
        result = prime * result + ((this.priceListId == null) ? 0 : this.priceListId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CkOutletDetails (");

        sb.append(id);
        sb.append(", ").append(activeStatus);
        sb.append(", ").append(activeStatusReason);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(extendedAttributes);
        sb.append(", ").append(lastModifiedTime);
        sb.append(", ").append(lob);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(source);
        sb.append(", ").append(version);
        sb.append(", ").append(account);
        sb.append(", ").append(address);
        sb.append(", ").append(beat);
        sb.append(", ").append(beatName);
        sb.append(", ").append(channel);
        sb.append(", ").append(contactName);
        sb.append(", ").append(contactno);
        sb.append(", ").append(displayAddress);
        sb.append(", ").append(frequency);
        sb.append(", ").append(gstNo);
        sb.append(", ").append(lastOrderDate);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(mapped);
        sb.append(", ").append(marketId);
        sb.append(", ").append(marketName);
        sb.append(", ").append(outletCategory);
        sb.append(", ").append(outletClass);
        sb.append(", ").append(outletcode);
        sb.append(", ").append(outletName);
        sb.append(", ").append(outletType);
        sb.append(", ").append(tinNo);
        sb.append(", ").append(locationHierarchy);
        sb.append(", ").append(loginid);
        sb.append(", ").append(accessibleby);
        sb.append(", ").append(accessibleBy);
        sb.append(", ").append(hash);
        sb.append(", ").append(coordinate);
        sb.append(", ").append(doo);
        sb.append(", ").append(dtype);
        sb.append(", ").append(hierarchy);
        sb.append(", ").append(changed);
        sb.append(", ").append(distributionChannel);
        sb.append(", ").append(outletDivision);
        sb.append(", ").append(soldTo);
        sb.append(", ").append(subChannel);
        sb.append(", ").append(subTerritory);
        sb.append(", ").append(blobKey);
        sb.append(", ").append(email);
        sb.append(", ").append(controlGroup);
        sb.append(", ").append(normalizedHierarchy);
        sb.append(", ").append(priceListId);

        sb.append(")");
        return sb.toString();
    }

    public CkUser getUserName(){
        return this.userName ;
    }

    public void setUserName(CkUser userName){
        this.userName = userName;
    }

    public List<CkHierarchyMetadata> getImmediateParent(){
        return this.immediateParent;
    }

    public void setImmediateParent(List<CkHierarchyMetadata> immediateParent){
        this.immediateParent = immediateParent;
    }


}



