/*
 * This file is generated by jOOQ.
 */
package com.salescode.jooq;


import com.fasterxml.jackson.databind.JsonNode;
import com.salescode.channelkart.converters.ActiveStatus;
import com.salescode.channelkart.models.CommonDataModel;
import com.salescode.jooq.generated.tables.pojos.CkUser;

import java.io.Serializable;
import java.util.Date;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CkSupplierMetadata extends CommonDataModel implements Serializable {

    private static final long serialVersionUID = 1L;

    private String       id;
    private ActiveStatus activeStatus;
    private String       activeStatusReason;
    private String       createdBy;
    private Date         creationTime;
    private JsonNode     extendedAttributes;
    private String       hash;
    private Date         lastModifiedTime;
    private String       lob;
    private String       modifiedBy;
    private String       source;
    private Integer      version;
    private String       level;
    private Integer      max;
    private Integer      min;
    private String       type;
    private String       userLoginid;
    private Byte         changed;
    private CkUser user;

    public CkSupplierMetadata() {}

    public CkSupplierMetadata(CkSupplierMetadata value) {
        this.id = value.id;
        this.activeStatus = value.activeStatus;
        this.activeStatusReason = value.activeStatusReason;
        this.createdBy = value.createdBy;
        this.creationTime = value.creationTime;
        this.extendedAttributes = value.extendedAttributes;
        this.hash = value.hash;
        this.lastModifiedTime = value.lastModifiedTime;
        this.lob = value.lob;
        this.modifiedBy = value.modifiedBy;
        this.source = value.source;
        this.version = value.version;
        this.level = value.level;
        this.max = value.max;
        this.min = value.min;
        this.type = value.type;
        this.userLoginid = value.userLoginid;
        this.changed = value.changed;
        this.user = value.user;
    }

    public CkSupplierMetadata(
        String       id,
        ActiveStatus activeStatus,
        String       activeStatusReason,
        String       createdBy,
        Date         creationTime,
        JsonNode     extendedAttributes,
        String       hash,
        Date         lastModifiedTime,
        String       lob,
        String       modifiedBy,
        String       source,
        Integer      version,
        String       level,
        Integer      max,
        Integer      min,
        String       type,
        String       userLoginid,
        Byte         changed,
        CkUser user
    ) {
        this.id = id;
        this.activeStatus = activeStatus;
        this.activeStatusReason = activeStatusReason;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.extendedAttributes = extendedAttributes;
        this.hash = hash;
        this.lastModifiedTime = lastModifiedTime;
        this.lob = lob;
        this.modifiedBy = modifiedBy;
        this.source = source;
        this.version = version;
        this.level = level;
        this.max = max;
        this.min = min;
        this.type = type;
        this.userLoginid = userLoginid;
        this.changed = changed;
        this.user = user;
    }

    /**
     * Getter for <code>ck_supplier_metadata.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>ck_supplier_metadata.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>ck_supplier_metadata.active_status</code>.
     */
    public ActiveStatus getActiveStatus() {
        return this.activeStatus;
    }

    /**
     * Setter for <code>ck_supplier_metadata.active_status</code>.
     */
    public void setActiveStatus(ActiveStatus activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * Getter for <code>ck_supplier_metadata.active_status_reason</code>.
     */
    public String getActiveStatusReason() {
        return this.activeStatusReason;
    }

    /**
     * Setter for <code>ck_supplier_metadata.active_status_reason</code>.
     */
    public void setActiveStatusReason(String activeStatusReason) {
        this.activeStatusReason = activeStatusReason;
    }

    /**
     * Getter for <code>ck_supplier_metadata.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>ck_supplier_metadata.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>ck_supplier_metadata.creation_time</code>.
     */
    public Date getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>ck_supplier_metadata.creation_time</code>.
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>ck_supplier_metadata.extended_attributes</code>.
     */
    public JsonNode getExtendedAttributes() {
        return this.extendedAttributes;
    }

    /**
     * Setter for <code>ck_supplier_metadata.extended_attributes</code>.
     */
    public void setExtendedAttributes(JsonNode extendedAttributes) {
        this.extendedAttributes = extendedAttributes;
    }

    /**
     * Getter for <code>ck_supplier_metadata.hash</code>.
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>ck_supplier_metadata.hash</code>.
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Getter for <code>ck_supplier_metadata.last_modified_time</code>.
     */
    public Date getLastModifiedTime() {
        return this.lastModifiedTime;
    }

    /**
     * Setter for <code>ck_supplier_metadata.last_modified_time</code>.
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * Getter for <code>ck_supplier_metadata.lob</code>.
     */
    public String getLob() {
        return this.lob;
    }

    /**
     * Setter for <code>ck_supplier_metadata.lob</code>.
     */
    public void setLob(String lob) {
        this.lob = lob;
    }

    /**
     * Getter for <code>ck_supplier_metadata.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>ck_supplier_metadata.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>ck_supplier_metadata.source</code>.
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>ck_supplier_metadata.source</code>.
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Getter for <code>ck_supplier_metadata.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>ck_supplier_metadata.version</code>.
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for <code>ck_supplier_metadata.level</code>.
     */
    public String getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>ck_supplier_metadata.level</code>.
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * Getter for <code>ck_supplier_metadata.max</code>.
     */
    public Integer getMax() {
        return this.max;
    }

    /**
     * Setter for <code>ck_supplier_metadata.max</code>.
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * Getter for <code>ck_supplier_metadata.min</code>.
     */
    public Integer getMin() {
        return this.min;
    }

    /**
     * Setter for <code>ck_supplier_metadata.min</code>.
     */
    public void setMin(Integer min) {
        this.min = min;
    }

    /**
     * Getter for <code>ck_supplier_metadata.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>ck_supplier_metadata.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>ck_supplier_metadata.user_loginid</code>.
     */
    public String getUserLoginid() {
        return this.userLoginid;
    }

    /**
     * Setter for <code>ck_supplier_metadata.user_loginid</code>.
     */
    public void setUserLoginid(String userLoginid) {
        this.userLoginid = userLoginid;
    }

    /**
     * Getter for <code>ck_supplier_metadata.changed</code>.
     */
    public Byte getChanged() {
        return this.changed;
    }

    /**
     * Setter for <code>ck_supplier_metadata.changed</code>.
     */
    public void setChanged(Byte changed) {
        this.changed = changed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CkSupplierMetadata (");

        sb.append(id);
        sb.append(", ").append(activeStatus);
        sb.append(", ").append(activeStatusReason);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(extendedAttributes);
        sb.append(", ").append(hash);
        sb.append(", ").append(lastModifiedTime);
        sb.append(", ").append(lob);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(source);
        sb.append(", ").append(version);
        sb.append(", ").append(level);
        sb.append(", ").append(max);
        sb.append(", ").append(min);
        sb.append(", ").append(type);
        sb.append(", ").append(userLoginid);
        sb.append(", ").append(changed);

        sb.append(")");
        return sb.toString();
    }

    public CkUser getUser() {
        return user;
    }
    /**
     * @param user the user to set
     */
    public void setUser(CkUser user) {
        this.user = user;
    }
}
