/*
 * This file is generated by jOOQ.
 */
package com.salescode.jooq;


import com.fasterxml.jackson.databind.JsonNode;
import com.salescode.channelkart.converters.ActiveStatus;

import com.salescode.jooq.generated.tables.pojos.CkHierarchyMetadata;

import java.util.*;
import java.util.stream.Collectors;

import org.jooq.DSLContext;
import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CkUserWrapper  {

    private static final long serialVersionUID = 1L;
    private transient List<CkHierarchyMetadata> immediateParent;
    private transient Set<String> designation;
    private String id;
    private ActiveStatus activeStatus;
    private String activeStatusReason;
    private String createdBy;
    private Date creationTime;
    private JsonNode extendedAttributes;
    private Date lastModifiedTime;
    private String lob;
    private String modifiedBy;
    private Integer version;
    private String address;
    private String contactType;
    private String countryCode;
    private String email;
    private String hierarchy;
    private Date lastPasswordResetDate;
    private String loginid;
    private String mobile;
    private String name;
    private String password;
    private String useraccountid;
    private String usercontext;
    private String webcontext;
    private String locationHierarchy;
    private String source;
    private String registeredNumber;
    private String facebookpsid;
    private JSON accessibleBy;
    private String hash;
    private String dialCode;
    private String ssoId;
    private String deviceId;
    private Byte verified;
    private Date doa;
    private Date dob;
    private String assignedHierarchy;
    private Byte changed;
    private Boolean blocked;
    private String normalizedHierarchy;
    private String alternateId;
    private String externalReferenceId;
    private String reportPassword;

    public CkUserWrapper() {}

    public CkUserWrapper(CkUser value, DSLContext dsl) {
        this.id = value.getId();
        this.activeStatus = value.getActiveStatus();
        this.activeStatusReason = value.getActiveStatusReason();
        this.createdBy = value.getCreatedBy();
        this.creationTime = value.getCreationTime();
        this.extendedAttributes = value.getExtendedAttributes();
        this.lastModifiedTime = value.getLastModifiedTime();
        this.lob = value.getLob();
        this.modifiedBy = value.getModifiedBy();
        this.version = value.getVersion();
        this.address = value.getAddress();
        this.contactType = value.getContactType();
        this.countryCode = value.getCountryCode();
        this.email = value.getEmail();
        this.hierarchy = value.getHierarchy();
        this.lastPasswordResetDate = value.getLastPasswordResetDate();
        this.loginid = value.getLoginid();
        this.mobile = value.getMobile();
        this.name = value.getName();
        this.password = value.getPassword();
        this.useraccountid = value.getUseraccountid();
        this.usercontext = value.getUsercontext();
        this.webcontext = value.getWebcontext();
        this.locationHierarchy = value.getLocationHierarchy();
        this.source = value.getSource();
        this.registeredNumber = value.getRegisteredNumber();
        this.facebookpsid = value.getFacebookpsid();
        this.accessibleBy = value.getAccessibleBy();
        this.hash = value.getHash();
        this.dialCode = value.getDialCode();
        this.ssoId = value.getSsoId();
        this.deviceId = value.getDeviceId();
        this.verified = value.getVerified();
        this.doa = value.getDoa();
        this.dob = value.getDob();
        this.assignedHierarchy = value.getAssignedHierarchy();
        this.changed = value.getChanged();
        this.blocked = value.getBlocked();
        this.normalizedHierarchy = value.getNormalizedHierarchy();
        this.alternateId = value.getAlternateId();
        this.externalReferenceId = value.getExternalReferenceId();
        this.reportPassword = value.getReportPassword();
    }

    public CkUserWrapper(
            String id,
            ActiveStatus activeStatus,
            String activeStatusReason,
            String createdBy,
            Date creationTime,
            JsonNode extendedAttributes,
            Date lastModifiedTime,
            String lob,
            String modifiedBy,
            Integer version,
            String address,
            String contactType,
            String countryCode,
            String email,
            String hierarchy,
            Date lastPasswordResetDate,
            String loginid,
            String mobile,
            String name,
            String password,
            String useraccountid,
            String usercontext,
            String webcontext,
            String locationHierarchy,
            String source,
            String registeredNumber,
            String facebookpsid,
            JSON accessibleBy,
            String hash,
            String dialCode,
            String ssoId,
            String deviceId,
            Byte verified,
            Date doa,
            Date dob,
            String assignedHierarchy,
            Byte changed,
            Boolean blocked,
            String normalizedHierarchy,
            String alternateId,
            String externalReferenceId,
            String reportPassword
    ) {
        this.id = id;
        this.activeStatus = activeStatus;
        this.activeStatusReason = activeStatusReason;
        this.createdBy = createdBy;
        this.creationTime = creationTime;
        this.extendedAttributes = extendedAttributes;
        this.lastModifiedTime = lastModifiedTime;
        this.lob = lob;
        this.modifiedBy = modifiedBy;
        this.version = version;
        this.address = address;
        this.contactType = contactType;
        this.countryCode = countryCode;
        this.email = email;
        this.hierarchy = hierarchy;
        this.lastPasswordResetDate = lastPasswordResetDate;
        this.loginid = loginid;
        this.mobile = mobile;
        this.name = name;
        this.password = password;
        this.useraccountid = useraccountid;
        this.usercontext = usercontext;
        this.webcontext = webcontext;
        this.locationHierarchy = locationHierarchy;
        this.source = source;
        this.registeredNumber = registeredNumber;
        this.facebookpsid = facebookpsid;
        this.accessibleBy = accessibleBy;
        this.hash = hash;
        this.dialCode = dialCode;
        this.ssoId = ssoId;
        this.deviceId = deviceId;
        this.verified = verified;
        this.doa = doa;
        this.dob = dob;
        this.assignedHierarchy = assignedHierarchy;
        this.changed = changed;
        this.blocked = blocked;
        this.normalizedHierarchy = normalizedHierarchy;
        this.alternateId = alternateId;
        this.externalReferenceId = externalReferenceId;
        this.reportPassword = reportPassword;
    }

    /**
     * Getter for <code>ck_user.id</code>.
     */
    
    
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>ck_user.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>ck_user.active_status</code>.
     */
    public ActiveStatus getActiveStatus() {
        return this.activeStatus;
    }

    /**
     * Setter for <code>ck_user.active_status</code>.
     */
    public void setActiveStatus(ActiveStatus activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * Getter for <code>ck_user.active_status_reason</code>.
     */
    
    public String getActiveStatusReason() {
        return this.activeStatusReason;
    }

    /**
     * Setter for <code>ck_user.active_status_reason</code>.
     */
    public void setActiveStatusReason(String activeStatusReason) {
        this.activeStatusReason = activeStatusReason;
    }

    /**
     * Getter for <code>ck_user.created_by</code>.
     */
    
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>ck_user.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>ck_user.creation_time</code>.
     */
    public Date getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>ck_user.creation_time</code>.
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>ck_user.extended_attributes</code>.
     */
    public JsonNode getExtendedAttributes() {
        return this.extendedAttributes;
    }

    /**
     * Setter for <code>ck_user.extended_attributes</code>.
     */
    public void setExtendedAttributes(JsonNode extendedAttributes) {
        this.extendedAttributes = extendedAttributes;
    }

    /**
     * Getter for <code>ck_user.last_modified_time</code>.
     */
    public Date getLastModifiedTime() {
        return this.lastModifiedTime;
    }

    /**
     * Setter for <code>ck_user.last_modified_time</code>.
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * Getter for <code>ck_user.lob</code>.
     */
    
    public String getLob() {
        return this.lob;
    }

    /**
     * Setter for <code>ck_user.lob</code>.
     */
    public void setLob(String lob) {
        this.lob = lob;
    }

    /**
     * Getter for <code>ck_user.modified_by</code>.
     */
    
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>ck_user.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>ck_user.version</code>.
     */
    
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>ck_user.version</code>.
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for <code>ck_user.address</code>.
     */
    
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>ck_user.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>ck_user.contact_type</code>.
     */
    
    public String getContactType() {
        return this.contactType;
    }

    /**
     * Setter for <code>ck_user.contact_type</code>.
     */
    public void setContactType(String contactType) {
        this.contactType = contactType;
    }

    /**
     * Getter for <code>ck_user.country_code</code>.
     */
    
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>ck_user.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>ck_user.email</code>.
     */
    
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>ck_user.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>ck_user.hierarchy</code>.
     */
    public String getHierarchy() {
        return this.hierarchy;
    }

    /**
     * Setter for <code>ck_user.hierarchy</code>.
     */
    public void setHierarchy(String hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for <code>ck_user.last_password_reset_date</code>.
     */
    public Date getLastPasswordResetDate() {
        return this.lastPasswordResetDate;
    }

    /**
     * Setter for <code>ck_user.last_password_reset_date</code>.
     */
    public void setLastPasswordResetDate(Date lastPasswordResetDate) {
        this.lastPasswordResetDate = lastPasswordResetDate;
    }

    /**
     * Getter for <code>ck_user.loginid</code>.
     */
    
    
    public String getLoginid() {
        return this.loginid;
    }

    /**
     * Setter for <code>ck_user.loginid</code>.
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }

    /**
     * Getter for <code>ck_user.mobile</code>.
     */
    
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>ck_user.mobile</code>.
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Getter for <code>ck_user.name</code>.
     */
    
    
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>ck_user.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>ck_user.password</code>.
     */
    
    
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>ck_user.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>ck_user.useraccountid</code>.
     */
    
    
    public String getUseraccountid() {
        return this.useraccountid;
    }

    /**
     * Setter for <code>ck_user.useraccountid</code>.
     */
    public void setUseraccountid(String useraccountid) {
        this.useraccountid = useraccountid;
    }

    /**
     * Getter for <code>ck_user.usercontext</code>.
     */
    
    public String getUsercontext() {
        return this.usercontext;
    }

    /**
     * Setter for <code>ck_user.usercontext</code>.
     */
    public void setUsercontext(String usercontext) {
        this.usercontext = usercontext;
    }

    /**
     * Getter for <code>ck_user.webcontext</code>.
     */
    
    public String getWebcontext() {
        return this.webcontext;
    }

    /**
     * Setter for <code>ck_user.webcontext</code>.
     */
    public void setWebcontext(String webcontext) {
        this.webcontext = webcontext;
    }

    /**
     * Getter for <code>ck_user.location_hierarchy</code>.
     */
    
    public String getLocationHierarchy() {
        return this.locationHierarchy;
    }

    /**
     * Setter for <code>ck_user.location_hierarchy</code>.
     */
    public void setLocationHierarchy(String locationHierarchy) {
        this.locationHierarchy = locationHierarchy;
    }

    /**
     * Getter for <code>ck_user.source</code>.
     */
    
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>ck_user.source</code>.
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Getter for <code>ck_user.registered_number</code>.
     */
    
    public String getRegisteredNumber() {
        return this.registeredNumber;
    }

    /**
     * Setter for <code>ck_user.registered_number</code>.
     */
    public void setRegisteredNumber(String registeredNumber) {
        this.registeredNumber = registeredNumber;
    }

    /**
     * Getter for <code>ck_user.facebookpsid</code>.
     */
    
    public String getFacebookpsid() {
        return this.facebookpsid;
    }

    /**
     * Setter for <code>ck_user.facebookpsid</code>.
     */
    public void setFacebookpsid(String facebookpsid) {
        this.facebookpsid = facebookpsid;
    }

    /**
     * Getter for <code>ck_user.accessible_by</code>.
     */
    public JSON getAccessibleBy() {
        return this.accessibleBy;
    }

    /**
     * Setter for <code>ck_user.accessible_by</code>.
     */
    public void setAccessibleBy(JSON accessibleBy) {
        this.accessibleBy = accessibleBy;
    }

    /**
     * Getter for <code>ck_user.hash</code>.
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>ck_user.hash</code>.
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Getter for <code>ck_user.dial_code</code>.
     */
    
    public String getDialCode() {
        return this.dialCode;
    }

    /**
     * Setter for <code>ck_user.dial_code</code>.
     */
    public void setDialCode(String dialCode) {
        this.dialCode = dialCode;
    }

    /**
     * Getter for <code>ck_user.sso_id</code>.
     */
    
    public String getSsoId() {
        return this.ssoId;
    }

    /**
     * Setter for <code>ck_user.sso_id</code>.
     */
    public void setSsoId(String ssoId) {
        this.ssoId = ssoId;
    }

    /**
     * Getter for <code>ck_user.device_id</code>.
     */
    
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Setter for <code>ck_user.device_id</code>.
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for <code>ck_user.verified</code>.
     */
    public Byte getVerified() {
        return this.verified;
    }

    /**
     * Setter for <code>ck_user.verified</code>.
     */
    public void setVerified(Byte verified) {
        this.verified = verified;
    }

    /**
     * Getter for <code>ck_user.doa</code>.
     */
    public Date getDoa() {
        return this.doa;
    }

    /**
     * Setter for <code>ck_user.doa</code>.
     */
    public void setDoa(Date doa) {
        this.doa = doa;
    }

    /**
     * Getter for <code>ck_user.dob</code>.
     */
    public Date getDob() {
        return this.dob;
    }

    /**
     * Setter for <code>ck_user.dob</code>.
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * Getter for <code>ck_user.assigned_hierarchy</code>.
     */
    public String getAssignedHierarchy() {
        return this.assignedHierarchy;
    }

    /**
     * Setter for <code>ck_user.assigned_hierarchy</code>.
     */
    public void setAssignedHierarchy(String assignedHierarchy) {
        this.assignedHierarchy = assignedHierarchy;
    }

    /**
     * Getter for <code>ck_user.changed</code>.
     */
    public Byte getChanged() {
        return this.changed;
    }

    /**
     * Setter for <code>ck_user.changed</code>.
     */
    public void setChanged(Byte changed) {
        this.changed = changed;
    }

    /**
     * Getter for <code>ck_user.blocked</code>.
     */
    public Boolean getBlocked() {
        return this.blocked;
    }

    /**
     * Setter for <code>ck_user.blocked</code>.
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

    /**
     * Getter for <code>ck_user.normalized_hierarchy</code>.
     */
    public String getNormalizedHierarchy() {
        return this.normalizedHierarchy;
    }

    /**
     * Setter for <code>ck_user.normalized_hierarchy</code>.
     */
    public void setNormalizedHierarchy(String normalizedHierarchy) {
        this.normalizedHierarchy = normalizedHierarchy;
    }

    /**
     * Getter for <code>ck_user.alternate_id</code>.
     */
    
    public String getAlternateId() {
        return this.alternateId;
    }

    /**
     * Setter for <code>ck_user.alternate_id</code>.
     */
    public void setAlternateId(String alternateId) {
        this.alternateId = alternateId;
    }

    /**
     * Getter for <code>ck_user.external_reference_id</code>.
     */
    
    public String getExternalReferenceId() {
        return this.externalReferenceId;
    }

    /**
     * Setter for <code>ck_user.external_reference_id</code>.
     */
    public void setExternalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
    }

    /**
     * Getter for <code>ck_user.report_password</code>.
     */
    
    public String getReportPassword() {
        return this.reportPassword;
    }

    /**
     * Setter for <code>ck_user.report_password</code>.
     */
    public void setReportPassword(String reportPassword) {
        this.reportPassword = reportPassword;
    }

//    @Override
//    public boolean equals(Object obj) {
//        if (this == obj)
//            return true;
//        if (obj == null)
//            return false;
//        if (getClass() != obj.getClass())
//            return false;
//        final CkUser other = (CkUser) obj;
//        if (this.id == null) {
//            if (other.id != null)
//                return false;
//        }
//        else if (!this.id.equals(other.id))
//            return false;
//        if (this.activeStatus == null) {
//            if (other.activeStatus != null)
//                return false;
//        }
//        else if (!this.activeStatus.equals(other.activeStatus))
//            return false;
//        if (this.activeStatusReason == null) {
//            if (other.activeStatusReason != null)
//                return false;
//        }
//        else if (!this.activeStatusReason.equals(other.activeStatusReason))
//            return false;
//        if (this.createdBy == null) {
//            if (other.createdBy != null)
//                return false;
//        }
//        else if (!this.createdBy.equals(other.createdBy))
//            return false;
//        if (this.creationTime == null) {
//            if (other.creationTime != null)
//                return false;
//        }
//        else if (!this.creationTime.equals(other.creationTime))
//            return false;
//        if (this.extendedAttributes == null) {
//            if (other.extendedAttributes != null)
//                return false;
//        }
//        else if (!this.extendedAttributes.equals(other.extendedAttributes))
//            return false;
//        if (this.lastModifiedTime == null) {
//            if (other.lastModifiedTime != null)
//                return false;
//        }
//        else if (!this.lastModifiedTime.equals(other.lastModifiedTime))
//            return false;
//        if (this.lob == null) {
//            if (other.lob != null)
//                return false;
//        }
//        else if (!this.lob.equals(other.lob))
//            return false;
//        if (this.modifiedBy == null) {
//            if (other.modifiedBy != null)
//                return false;
//        }
//        else if (!this.modifiedBy.equals(other.modifiedBy))
//            return false;
//        if (this.version == null) {
//            if (other.version != null)
//                return false;
//        }
//        else if (!this.version.equals(other.version))
//            return false;
//        if (this.address == null) {
//            if (other.address != null)
//                return false;
//        }
//        else if (!this.address.equals(other.address))
//            return false;
//        if (this.contactType == null) {
//            if (other.contactType != null)
//                return false;
//        }
//        else if (!this.contactType.equals(other.contactType))
//            return false;
//        if (this.countryCode == null) {
//            if (other.countryCode != null)
//                return false;
//        }
//        else if (!this.countryCode.equals(other.countryCode))
//            return false;
//        if (this.email == null) {
//            if (other.email != null)
//                return false;
//        }
//        else if (!this.email.equals(other.email))
//            return false;
//        if (this.hierarchy == null) {
//            if (other.hierarchy != null)
//                return false;
//        }
//        else if (!this.hierarchy.equals(other.hierarchy))
//            return false;
//        if (this.lastPasswordResetDate == null) {
//            if (other.lastPasswordResetDate != null)
//                return false;
//        }
//        else if (!this.lastPasswordResetDate.equals(other.lastPasswordResetDate))
//            return false;
//        if (this.loginid == null) {
//            if (other.loginid != null)
//                return false;
//        }
//        else if (!this.loginid.equals(other.loginid))
//            return false;
//        if (this.mobile == null) {
//            if (other.mobile != null)
//                return false;
//        }
//        else if (!this.mobile.equals(other.mobile))
//            return false;
//        if (this.name == null) {
//            if (other.name != null)
//                return false;
//        }
//        else if (!this.name.equals(other.name))
//            return false;
//        if (this.password == null) {
//            if (other.password != null)
//                return false;
//        }
//        else if (!this.password.equals(other.password))
//            return false;
//        if (this.useraccountid == null) {
//            if (other.useraccountid != null)
//                return false;
//        }
//        else if (!this.useraccountid.equals(other.useraccountid))
//            return false;
//        if (this.usercontext == null) {
//            if (other.usercontext != null)
//                return false;
//        }
//        else if (!this.usercontext.equals(other.usercontext))
//            return false;
//        if (this.webcontext == null) {
//            if (other.webcontext != null)
//                return false;
//        }
//        else if (!this.webcontext.equals(other.webcontext))
//            return false;
//        if (this.locationHierarchy == null) {
//            if (other.locationHierarchy != null)
//                return false;
//        }
//        else if (!this.locationHierarchy.equals(other.locationHierarchy))
//            return false;
//        if (this.source == null) {
//            if (other.source != null)
//                return false;
//        }
//        else if (!this.source.equals(other.source))
//            return false;
//        if (this.registeredNumber == null) {
//            if (other.registeredNumber != null)
//                return false;
//        }
//        else if (!this.registeredNumber.equals(other.registeredNumber))
//            return false;
//        if (this.facebookpsid == null) {
//            if (other.facebookpsid != null)
//                return false;
//        }
//        else if (!this.facebookpsid.equals(other.facebookpsid))
//            return false;
//        if (this.accessibleBy == null) {
//            if (other.accessibleBy != null)
//                return false;
//        }
//        else if (!this.accessibleBy.equals(other.accessibleBy))
//            return false;
//        if (this.hash == null) {
//            if (other.hash != null)
//                return false;
//        }
//        else if (!this.hash.equals(other.hash))
//            return false;
//        if (this.dialCode == null) {
//            if (other.dialCode != null)
//                return false;
//        }
//        else if (!this.dialCode.equals(other.dialCode))
//            return false;
//        if (this.ssoId == null) {
//            if (other.ssoId != null)
//                return false;
//        }
//        else if (!this.ssoId.equals(other.ssoId))
//            return false;
//        if (this.deviceId == null) {
//            if (other.deviceId != null)
//                return false;
//        }
//        else if (!this.deviceId.equals(other.deviceId))
//            return false;
//        if (this.verified == null) {
//            if (other.verified != null)
//                return false;
//        }
//        else if (!this.verified.equals(other.verified))
//            return false;
//        if (this.doa == null) {
//            if (other.doa != null)
//                return false;
//        }
//        else if (!this.doa.equals(other.doa))
//            return false;
//        if (this.dob == null) {
//            if (other.dob != null)
//                return false;
//        }
//        else if (!this.dob.equals(other.dob))
//            return false;
//        if (this.assignedHierarchy == null) {
//            if (other.assignedHierarchy != null)
//                return false;
//        }
//        else if (!this.assignedHierarchy.equals(other.assignedHierarchy))
//            return false;
//        if (this.changed == null) {
//            if (other.changed != null)
//                return false;
//        }
//        else if (!this.changed.equals(other.changed))
//            return false;
//        if (this.blocked == null) {
//            if (other.blocked != null)
//                return false;
//        }
//        else if (!this.blocked.equals(other.blocked))
//            return false;
//        if (this.normalizedHierarchy == null) {
//            if (other.normalizedHierarchy != null)
//                return false;
//        }
//        else if (!this.normalizedHierarchy.equals(other.normalizedHierarchy))
//            return false;
//        if (this.alternateId == null) {
//            if (other.alternateId != null)
//                return false;
//        }
//        else if (!this.alternateId.equals(other.alternateId))
//            return false;
//        if (this.externalReferenceId == null) {
//            if (other.externalReferenceId != null)
//                return false;
//        }
//        else if (!this.externalReferenceId.equals(other.externalReferenceId))
//            return false;
//        if (this.reportPassword == null) {
//            if (other.reportPassword != null)
//                return false;
//        }
//        else if (!this.reportPassword.equals(other.reportPassword))
//            return false;
//        return true;
//    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.activeStatus == null) ? 0 : this.activeStatus.hashCode());
        result = prime * result + ((this.activeStatusReason == null) ? 0 : this.activeStatusReason.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.creationTime == null) ? 0 : this.creationTime.hashCode());
        result = prime * result + ((this.extendedAttributes == null) ? 0 : this.extendedAttributes.hashCode());
        result = prime * result + ((this.lastModifiedTime == null) ? 0 : this.lastModifiedTime.hashCode());
        result = prime * result + ((this.lob == null) ? 0 : this.lob.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        result = prime * result + ((this.contactType == null) ? 0 : this.contactType.hashCode());
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.hierarchy == null) ? 0 : this.hierarchy.hashCode());
        result = prime * result + ((this.lastPasswordResetDate == null) ? 0 : this.lastPasswordResetDate.hashCode());
        result = prime * result + ((this.loginid == null) ? 0 : this.loginid.hashCode());
        result = prime * result + ((this.mobile == null) ? 0 : this.mobile.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.useraccountid == null) ? 0 : this.useraccountid.hashCode());
        result = prime * result + ((this.usercontext == null) ? 0 : this.usercontext.hashCode());
        result = prime * result + ((this.webcontext == null) ? 0 : this.webcontext.hashCode());
        result = prime * result + ((this.locationHierarchy == null) ? 0 : this.locationHierarchy.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.registeredNumber == null) ? 0 : this.registeredNumber.hashCode());
        result = prime * result + ((this.facebookpsid == null) ? 0 : this.facebookpsid.hashCode());
        result = prime * result + ((this.accessibleBy == null) ? 0 : this.accessibleBy.hashCode());
        result = prime * result + ((this.hash == null) ? 0 : this.hash.hashCode());
        result = prime * result + ((this.dialCode == null) ? 0 : this.dialCode.hashCode());
        result = prime * result + ((this.ssoId == null) ? 0 : this.ssoId.hashCode());
        result = prime * result + ((this.deviceId == null) ? 0 : this.deviceId.hashCode());
        result = prime * result + ((this.verified == null) ? 0 : this.verified.hashCode());
        result = prime * result + ((this.doa == null) ? 0 : this.doa.hashCode());
        result = prime * result + ((this.dob == null) ? 0 : this.dob.hashCode());
        result = prime * result + ((this.assignedHierarchy == null) ? 0 : this.assignedHierarchy.hashCode());
        result = prime * result + ((this.changed == null) ? 0 : this.changed.hashCode());
        result = prime * result + ((this.blocked == null) ? 0 : this.blocked.hashCode());
        result = prime * result + ((this.normalizedHierarchy == null) ? 0 : this.normalizedHierarchy.hashCode());
        result = prime * result + ((this.alternateId == null) ? 0 : this.alternateId.hashCode());
        result = prime * result + ((this.externalReferenceId == null) ? 0 : this.externalReferenceId.hashCode());
        result = prime * result + ((this.reportPassword == null) ? 0 : this.reportPassword.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CkUser (");

        sb.append(id);
        sb.append(", ").append(activeStatus);
        sb.append(", ").append(activeStatusReason);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(extendedAttributes);
        sb.append(", ").append(lastModifiedTime);
        sb.append(", ").append(lob);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(address);
        sb.append(", ").append(contactType);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(email);
        sb.append(", ").append(hierarchy);
        sb.append(", ").append(lastPasswordResetDate);
        sb.append(", ").append(loginid);
        sb.append(", ").append(mobile);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(useraccountid);
        sb.append(", ").append(usercontext);
        sb.append(", ").append(webcontext);
        sb.append(", ").append(locationHierarchy);
        sb.append(", ").append(source);
        sb.append(", ").append(registeredNumber);
        sb.append(", ").append(facebookpsid);
        sb.append(", ").append(accessibleBy);
        sb.append(", ").append(hash);
        sb.append(", ").append(dialCode);
        sb.append(", ").append(ssoId);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(verified);
        sb.append(", ").append(doa);
        sb.append(", ").append(dob);
        sb.append(", ").append(assignedHierarchy);
        sb.append(", ").append(changed);
        sb.append(", ").append(blocked);
        sb.append(", ").append(normalizedHierarchy);
        sb.append(", ").append(alternateId);
        sb.append(", ").append(externalReferenceId);
        sb.append(", ").append(reportPassword);

        sb.append(")");
        return sb.toString();
    }
    public String getLoginId() {
        return loginid;
    }


    public List<CkHierarchyMetadata> getImmediateParent() {
        if (this.immediateParent == null && this.hierarchy != null) {
            List<String> parents = findParents(hierarchy);
            List<CkHierarchyMetadata> hierarchyMetaDataList = parents.stream().map(parent -> {
                CkHierarchyMetadata hierarchyMetaData = new CkHierarchyMetadata();
                hierarchyMetaData.setImmediateParent(parent);
                return hierarchyMetaData;
            }).collect(Collectors.toList());
            this.setImmediateParent(hierarchyMetaDataList);
        }
        return immediateParent;
    }
    public void setImmediateParent(List<CkHierarchyMetadata> immediateParent){
        this.immediateParent = immediateParent;
    }
    public static Optional<String> getImmediateParentFromHierarchy(String hierarchy) {
        String[] splitHierarchy = hierarchy.split(" > ");
        if (splitHierarchy.length > 1) {
            return Optional.of(splitHierarchy[1].trim());
        }
        return Optional.empty();
    }

    public static List<String> findParents(String hierarchy) {
        return Arrays.stream(hierarchy.split(","))
                .map(String::trim)
                .map(CkUserWrapper::getImmediateParentFromHierarchy)
                .flatMap(Optional::stream)
                .distinct()
                .collect(Collectors.toList());
    }

    public String hash() {
        return loginid ;
//                + super.hash();
    }

    public Set<String> getDesignation(){
        return this.designation;
    }

    public void setDesignation(Set<String> designation){
        this.designation = designation;
    }
}
