/*
 * This file is generated by jOOQ.
 */
package com.salescode.dim.jooq.impl;


import com.salescode.dim.jooq.generated.tables.pojos.Location;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Getter
@Setter
public class OutletDetails extends com.salescode.dim.jooq.generated.tables.pojos.OutletDetails implements Serializable {

    private List<HierarchyMetadata> immediateParent;
    private User userName;
    private Location location;


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString());
        sb.deleteCharAt(sb.length() - 1);
        sb.append(", ").append(immediateParent);
        sb.append(", ").append(userName);
        sb.append(", ").append(location);
        sb.append(")");
        return sb.toString();
    }

}
