<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.8</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.salescode</groupId>
    <artifactId>dis</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>dis</name>
    <description>Salescode data integration with flink</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>11</java.version>
        <flink.version>1.20.0</flink.version>
        <log4j2.version>2.19.0</log4j2.version>
        <jooq.version>3.16.23</jooq.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-streaming-java -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-connector-files -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-files</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-json</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-connector-jdbc -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc</artifactId>
            <version>3.2.0-1.19</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-s3-fs-hadoop -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-s3-fs-hadoop</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-json</artifactId>
            <version>${flink.version}</version> <!-- Replace with your Flink version -->
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-connector-kafka -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka</artifactId>
            <version>3.3.0-1.20</version>
        </dependency>
        <!-- <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency> -->
        <!-- AWS SDK for S3 -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>2.29.2</version>
        </dependency>

        <!-- JOOQ -->
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>${jooq.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jooq</artifactId>
        </dependency>


        <!-- MySQL Driver Dependency (since you're using MySQL) -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.32</version>
        </dependency>

        <!-- MySQL Driver Dependency (since you're using MySQL) -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.32</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Additional Libraries -->
        <dependency>
            <groupId>com.github.jknack</groupId>
            <artifactId>handlebars</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.27.0-GA</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
        </dependency>
        <dependency>
            <groupId>javax.persistence</groupId>
            <artifactId>javax.persistence-api</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20231013</version>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Maven Shade Plugin for creating a Fat JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <id>shade-jar-with-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.salescode.dis.FlinkApplication</mainClass>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <excludes>
                                        <exclude>
                                            ch/qos/logback/logback-*.jar
                                        </exclude>
                                        <exclude>
                                            ch/qos/logback/logback-*.jar
                                        </exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
<!--                    <execution>-->
<!--                        <goals>-->
<!--                            <goal>generate</goal>-->
<!--                        </goals>-->
<!--                        <phase>process-classes</phase> &lt;!&ndash; Change the phase to process-classes &ndash;&gt;-->
<!--                    </execution>-->
                </executions>
                <configuration>
                    <jdbc>
                        <driver>com.mysql.cj.jdbc.Driver</driver>
                        <url>jdbc:mysql://localhost:3306/ckroot</url>
                        <user>root</user>
                        <password>toor1234</password>
                    </jdbc>
                    <generator>
                        <!--                        <name>org.jooq.codegen.DefaultGenerator</name>-->
                        <database>
                            <name>org.jooq.meta.mysql.MySQLDatabase</name>
                            <inputSchema>ckroot</inputSchema>
                            <!--                            <includes>ckroot</includes>-->
                            <outputSchemaToDefault>true</outputSchemaToDefault>
                            <forcedTypes>
                                <forcedType>
                                    <userType>com.salescode.channelkart.converters.ActiveStatus</userType>
                                    <converter>com.salescode.jooq.ActiveStatusConverter</converter>
                                    <includeExpression>ACTIVE_STATUS</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <userType>java.util.Date</userType>
                                    <converter>com.salescode.jooq.DateConverter</converter>
                                    <includeExpression>(.*Time)|doo|(.*Date)|doa|dob</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <userType>com.fasterxml.jackson.databind.JsonNode</userType>
                                    <converter>com.salescode.jooq.JsonNodeConverter</converter>
                                    <includeExpression>(.*ATTRIBUTES)|code|domain_values</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <userType>com.salescode.channelkart.converters.EnrichmentPhase</userType>
                                    <converter>com.salescode.jooq.EnrichmentPhaseConverter</converter>
                                    <includeExpression>phase</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <name></name>
                                    <expression>.*\.COORDINATE</expression>
                                    <types>POINT</types>
                                </forcedType>
                            </forcedTypes>
                        </database>
                        <generate>
                            <!--                            <defaultCatalog>false</defaultCatalog>-->
                            <!--                            <defaultSchema>true</defaultSchema>-->
                            <pojos>true</pojos>
                            <records>false</records>
                            <!--                            <generatedAnnotation>true</generatedAnnotation>-->
                            <!--                            <generatedAnnotationType>JAVAX_ANNOTATION_PROCESSING_GENERATED</generatedAnnotationType>-->
                            <!--                            <generatedAnnotationDate>true</generatedAnnotationDate>-->
                            <!--                            <generatedAnnotationJooqVersion>true</generatedAnnotationJooqVersion>-->
                            <!--                            <nullableAnnotation>true</nullableAnnotation>-->
                            <!--                            <nullableAnnotationType>javax.annotation.Nullable</nullableAnnotationType>-->
                            <!--                            <nonnullAnnotation>true</nonnullAnnotation>-->
                            <!--                            <nonnullAnnotationType>javax.annotation.Nonnull</nonnullAnnotationType>-->

                            <!--                            <jpaAnnotations>true</jpaAnnotations>-->
                            <!--                            <jpaVersion>${project.parent.version}}</jpaVersion>-->
                            <validationAnnotations>true</validationAnnotations>
                            <springAnnotations>true</springAnnotations>
                            <!--                            <springDao>true</springDao>-->

                            <!--                            <constructorPropertiesAnnotation>true</constructorPropertiesAnnotation>-->
                            <!--                            <constructorPropertiesAnnotationOnPojos>true</constructorPropertiesAnnotationOnPojos>-->
                            <!--                            <constructorPropertiesAnnotationOnRecords>true</constructorPropertiesAnnotationOnRecords>-->

                            <!--                            <fluentSetters>true</fluentSetters>-->
                        </generate>
                        <target>
                            <packageName>com.salescode.jooq.generated</packageName>
                            <directory>target/generated-sources/jooq</directory>
                        </target>
                        <strategy>
                            <name>com.salescode.jooq.CustomGeneratorStrategy</name>
                        </strategy>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>
