spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ckroot?currentSchema=ckroot
    username: root
    password: toor1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: MYSQL
  kafka:
    producer:
      bootstrap-servers: "164.52.202.184:9092"
      client-id: "dataintsvc-lob-entity"
    consumer:
      group-id: "dataintsvc-lob-entity"
      bootstrap-servers: "164.52.202.184:9092"
      enable-auto-commit: false
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3
      type: batch
      ack-mode: MANUAL
      idle-event-interval: 60000 # 5 minutes in milliseconds, triggers idle event
    template:
      default-topic: dead-letter-topic
  thread-pool:
    core-size: 10
    max-size: 20
    queue-capacity: 100 # Added queue size configuration

# Enable Prometheus or OpenTelemetry
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus, health
  otlp:
    metrics:
      export:
        enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

app:
  auto-shutdown: false
  kafka-topic: "test-topic"
