# Database configuration
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://demoaurora.c2szfgab1pix.ap-south-1.rds.amazonaws.com:3306/db_cokesademo?autoReconnect=true&nullCatalogMeansCurrent=true
jdbc.user=demockart
jdbc.password=09Nov2020#

# Schema patterns
schema.includePattern=((?i)^(ck_?(transformer.*|target.*|enrichment.*|validation.*|metadata.*|.*profile.*|location|hierarchy.*|auth_role|supplier_metadata|generic.*|customer_account|score_details|redeem_activity|product.*|discount.*|stock.*|generic_object|division|outlet_metadata|integration_history|division_roles|scheme.*|channel.*|division.*))|(ck_outlet_details_?(hierarchy.*)?|(ck_user_?(.*parent|roles|designation)?))|(credit_outlets))

schema.excludePattern=

# Input schema and target package
input.schema=db_cokesademo
bootstrap.servers=164.52.202.184:9092
target.package=com.salescode.dim.jooq.generated
target.directory=target/generated-sources/jooq
group.id=dataintegration-local

lob=cokesademo

entities=OutletDetails,OutletMetadata,Targets,GenericEntity,CreditOutlets

# Topic name for the input data ${lob}-${input.topic}; From this topic, it will be bifurcated to different topics based on the entity then consumed
# ${lob}-${input.topic}-${entity} e.g. ckunnatiuat-dataintegration-OutletDetails
# For failures, it will be pushed to ${lob}-${input.topic}-dlq e.g. dataintegration-ckunnatiuat-failure
# For events, it will be pushed to ${lob}-${input.topic}-events e.g. dataintegration-ckunnatiuat-events
input.topic=dataintegration
failure.topic=dataintegration-failure
event.topic=dataintegration-event
redisUrl=redis://localhost:6379
cacheClustered=false
INSIGHTS_INTEGRATION_IDLE_EVICTION_TTL_MINUTES=10
insights.topic=file-progress-updates-1
insights.enabled=true
publish.success.enabled=true
success.topic=int-success-streams

