config:
  s3:
    uri: "s3://salescode-dev-uat/dataintegration/{lob}/application.yaml"
    region: ap-south-1

logging:
  level:
    root: info

spring:
  application:
    name: disflink
  profiles:
    active: local
app:
  lob: ckuatunnati
  bundle:
    uri: "https://salescode-dev-uat.s3.ap-south-1.amazonaws.com/dataintegration/{lob}/dis-bundle.jar"
  kafka:
    bootstrap-servers: "164.52.202.184:9092"
    # bootstrap-servers: "localhost:9092"
    producer-txn-timeout: 60000
  jobs:
    from-kafka-to-db:
      consumer-group-id: lob-integration-consumer
      main-topic-name: flink-test
      dlq-topic-name: flink-test-dlt
      db:
        url: "jdbc:mysql://dev-rds.ck9zclkriezk.ap-south-1.rds.amazonaws.com:3306/ckunnatiuat"
        user: "ckuatadmin"
        password: "Uat12Oct#"
    from-s3-to-kafka:
      bucket-name: dataplatform-flink
      file-type: csv  # can be csv or excel
      file-key: SmileStore_20240905.csv
      topic: flink-test
      dead-letter-topic: flink-test-dlt
      flink:
        parallelism:
          main-topic: 1
          dead-letter-topic: 1
        restart:
          attempts: 3
          delay-seconds: 10
          strategy: fixed-delay