# Database configuration
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://uat-rds.cluster-ck9zclkriezk.ap-south-1.rds.amazonaws.com:3306/db_kgbpluat
jdbc.user=ckuatadmin
jdbc.password=Uat12Oct#25#
#jdbc.url = jdbc:mysql://13.126.121.57:3342/ckroot?autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
#jdbc.user = demockart
#jdbc.password = 09Nov2020#


#spring.datasource.url = jdbc:mysql://uat-rds.cluster-ck9zclkriezk.ap-south-1.rds.amazonaws.com:3306/ckroot?autoReconnect=true&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
#spring.datasource.password = Uat12Oct#25#
#spring.datasource.username = ckuatadmin
# Schema patterns
schema.includePattern=((?i)^(ck_?(transformer.*|target.*|enrichment.*|validation.*|metadata.*|.*profile.*|location|hierarchy.*|auth_role|supplier_metadata|generic.*|customer_account|channel_hierarchy_metadata|division|outlet_metadata|score_details|redeem_activity|integration_history|division_roles|scheme.*|channel.*|division.*))|(ck_outlet_details_?(hierarchy.*)?|(ck_user_?(.*parent|roles|designation)?)))

schema.excludePattern=

# Input schema and target package
input.schema=db_kgbpluat
bootstrap.servers=164.52.202.184:9092
target.package=com.salescode.dim.jooq.generated
target.directory=target/generated-sources/jooq
group.id=dataintegration-local

lob=kgbpluat

entities=Stock
channelkart.env=uat
channelkart.token=ckt-GQpr9LQhpd_0cHJcKoVBDGT8Hu8Bbflu-ikLN87wvC0GvxGOv-bO7clbBO3RvnEPn_aibcCzdnxAECr8aftngUJE0rMXQosirYoBvdcaUv3idG_lZ8je_npgg-fc7PD18H-ZBawZANpryCVXGr-LiDJmC5yULsCf2Wp1TJtnDgcYe0p72KiWdGaxcCm2wUH5YjgNxVKIJ4feyt1hAr6NdUgZbESV8af8TypvpbWbz1tFvfEazL_HXEvu9aor3br8WMEQpzH9vFE-xst0G-MV3HjMsmm_eIQjOyWLNc4JT9EmrtK3AOh9ckpIo3rO-T48P4q-XR9I4ilIGDdDJNqpcOrwQqjFTDu3ai20yeQ77XFC81we4GJLG9WDrbTXZQ7vLQOM8FbC6qezdgUfc9jwzo4fpP5bDQwnivjtI5EW1USn8bd6TkLUyJJayMtdSdEgNhj9ERtJ8wnkoOrypZbKPsIADMLpsTRxmOe48esK1uDMLSCCO62C6yd2szCp9YlpD4p8iQG4mRCpl2ZhllNEqKS6DfV0aF2pxJaFNdIawS7hIhtDevGZN9oWlrF6IzpE5Xls_sZvoni1e42m2wE5QQMRS_sKusit8eSM7f_ZN6mORP6KCPzH0gh3OYI0Of45lbVZF5wQbvUV89X1lXbOJFModGX8Yuwnvsc97Fri80zCo2cp9f2mfaxNSk8KSUvR5bAB9SwPxxV3pyqrgxwWYUgRArymO_8-ydj7DYtSmMlsDEpmpo-zrUDGXU_2jRnb6c4MrntfLBxN9cNWDaGYUpZmZIlKQpYT6DD9_ek7acPwxBA_YrZ4TL7A4sHzR4RnteapFb0W3ytUxK-3X782hQEPron9pOzb2IuvtLAIMudAoLj5pPKuDxdvA7jdHDV92xkQvVNO8wkG1nxmGgBZRvM-rV0ChXBOmlMK53ACrCiRICog_fmitRmOU3xcT3tBkC3RM2hC-xU5jcnyk4rr_tZHw_zVGHvRDW9eJNS8aiRgcW6ZJ_sOPD-x7-s3Lo463fmgQecFF5OE7Lx2NkMYXupEw4A1OWZzWO37SnGfqATVeUkJvaV1qoG8t0qWHrgTxaW-aJCy33J_r90fQBvmWC8wE2wZk7NWwfMpCZK-IaVwGoZgEvCAhaorNAirGNZtLez7s1FVpbpw-jEhJquaDuVx9pSFMw6C1xXei-Mru6Euw8qFy-_RxJyW6SPr3qiN7bbNUXfb0Jy85u-bjcmY7a14Fz6sm7aUNF6qESTjV8tvmfpyRQ15WjDRvpb9XZjTSOIiIdGzYkWD3kFFFwjqLQQin3Cljl72SV-AiY1s8TOv0tS_ue9dG6b8CLAcynWsK-CN0F0fY3GX8NN8QE1y9w==

# Topic name for the input data ${lob}-${input.topic}; From this topic, it will be bifurcated to different topics based on the entity then consumed
# ${lob}-${input.topic}-${entity} e.g. ckunnatiuat-dataintegration-OutletDetails
# For failures, it will be pushed to ${lob}-${input.topic}-dlq e.g. dataintegration-ckunnatiuat-failure
# For events, it will be pushed to ${lob}-${input.topic}-events e.g. dataintegration-ckunnatiuat-events
input.topic=dataintegration
failure.topic=dataintegration-failure
event.topic=dataintegration-event
redisUrl=redis://localhost:6379
cacheClustered=false
INSIGHTS_INTEGRATION_IDLE_EVICTION_TTL_MINUTES=10
publishConsumedMetrics.topic=file-progress-updates