# Database configuration
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://13.126.121.57:3342/db_hccbckinddemonew
jdbc.user=kbuddydemoadmin
jdbc.password=kBuddyDemo@#D23

# Schema patterns
schema.includePattern=((?i)^(ck_?(transformer.*|enrichment.*|validation.*|metadata.*|.*profile.*|location|hierarchy.*|auth_role|supplier_metadata|generic.*|customer_account|channel_hierarchy_metadata|division|integration_history|division_roles|scheme.*|channel.*|division.*))|(ck_outlet_details_?(hierarchy.*)?|(ck_user_?(.*parent|roles|designation)?)))
schema.excludePattern=

# Input schema and target package
input.schema=db_hccbckinddemonew
bootstrap.servers=164.52.202.184:9092
target.package=com.salescode.dim.jooq.generated
target.directory=target/generated-sources/jooq
group.id=dataintegration-local

lob=hccbckinddemo

entities=SchemeDefination

# Topic name for the input data ${lob}-${input.topic}; From this topic, it will be bifurcated to different topics based on the entity then consumed
# ${lob}-${input.topic}-${entity} e.g. ckunnatiuat-dataintegration-OutletDetails
# For failures, it will be pushed to ${lob}-${input.topic}-dlq e.g. dataintegration-ckunnatiuat-failure
# For events, it will be pushed to ${lob}-${input.topic}-events e.g. dataintegration-ckunnatiuat-events
input.topic=hccbckinduat-flink-stream
#entity.input.topic=hccbckinduat-flink-stream-SchemeDefination
failure.topic=dataintegration-failure-streams
event.topic=dataintegration-event
