config:
  s3:
    uri: "s3://dataplatform-flink/properties/test-lob/application.yaml"
    region: ap-south-1

logging:
  system: none

spring:
  application:
    name: disflink

app:
  lob: sample
  kafka:
    bootstrap-servers: "164.52.202.184:9092"
    # bootstrap-servers: "localhost:9092"
    producer-txn-timeout: 60000
  jobs:
    from-kafka-to-db:
      consumer-group-id: lob-integration-consumer
      main-topic-name: flink-test
      dlq-topic-name: flink-test-dlt
      db:
        url: "jdbc:mysql://mysql:3306/yourdatabase"
        user: "youruser"
        password: "youruserpassword"
    from-s3-to-kafka:
      bucket-name: dataplatform-flink
      file-type: csv  # can be csv or excel
      file-key: SmileStore_20240905.csv
      topic: flink-test
      dead-letter-topic: flink-test-dlt
      flink:
        parallelism:
          main-topic: 1
          dead-letter-topic: 1
        restart:
          attempts: 3
          delay-seconds: 10
          strategy: fixed-delay