/*
 * This file is generated by jOOQ.
 */
package com.salescode.jooq.impl;


import com.fasterxml.jackson.databind.JsonNode;
import com.salescode.channelkart.models.CommonDataModel;
import com.salescode.channelkart.models.enums.ActiveStatus;
import com.salescode.jooq.generated.tables.pojos.CkHierarchyMetadata;
import com.salescode.jooq.generated.tables.pojos.CkLocation;
import com.salescode.jooq.impl.CkUser;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Getter
@Setter
public class CkOutletDetails extends com.salescode.jooq.generated.tables.pojos.CkOutletDetails {

    private List<CkHierarchyMetadata> immediateParent;
    private CkUser userName;
    private CkLocation location;

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString());
        sb.deleteCharAt(sb.length() - 1);
        sb.append(", ").append(immediateParent);
        sb.append(", ").append(userName);
        sb.append(", ").append(location);
        sb.append(")");
        return sb.toString();
    }

}
