<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.8</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.salescode</groupId>
    <artifactId>jooq-generate</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jooq.version>3.16.23</jooq.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>${jooq.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jooq</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.32</version>
        </dependency>

    </dependencies>
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <plugins>
            <!-- Maven Shade Plugin for creating a Fat JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-classes</phase>
                    </execution>
                </executions>
                <configuration>
                    <jdbc>
                        <driver>com.mysql.cj.jdbc.Driver</driver>
                        <url>jdbc:mysql://localhost:3306/ckroot</url>
                        <user>root</user>
                        <password>toor1234</password>
                    </jdbc>
                    <generator>
                        <database>
                            <name>org.jooq.meta.mysql.MySQLDatabase</name>
                            <inputSchema>ckroot</inputSchema>
                            <outputSchemaToDefault>true</outputSchemaToDefault>
                            <forcedTypes>
                                <forcedType>
                                    <userType>com.salescode.channelkart.converters.ActiveStatus</userType>
                                    <converter>com.salescode.jooq.ActiveStatusConverter</converter>
                                    <includeExpression>ACTIVE_STATUS</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <userType>java.util.Date</userType>
                                    <converter>com.salescode.jooq.DateConverter</converter>
                                    <includeExpression>
                                        (last_modified|creation|last_order|last_password_reset)_(date|time)|doo|doa|dob
                                    </includeExpression>
                                </forcedType>
                                <forcedType>
                                    <userType>com.fasterxml.jackson.databind.JsonNode</userType>
                                    <converter>com.salescode.jooq.JsonNodeConverter</converter>
                                    <includeExpression>(.*attributes)|domain_values</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <userType>com.salescode.channelkart.converters.EnrichmentPhase</userType>
                                    <converter>com.salescode.jooq.EnrichmentPhaseConverter</converter>
                                    <includeExpression>phase</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <name></name>
                                    <expression>.*\.COORDINATE</expression>
                                    <types>POINT</types>
                                </forcedType>
                            </forcedTypes>
                        </database>
                        <generate>
                            <pojos>true</pojos>
                            <records>false</records>
                        </generate>
                        <target>
                            <packageName>com.salescode.jooq.generated</packageName>
                            <directory>target/generated-sources/jooq</directory>
                        </target>
                        <strategy>
                            <name>com.salescode.jooq.CustomGeneratorStrategy</name>
                        </strategy>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>