/*
 * This file is generated by jOOQ.
 */
package com.salescode.dim.jooq.impl;


import lombok.Getter;
import lombok.Setter;
import org.apache.flink.shaded.jackson2.com.fasterxml.jackson.annotation.JsonInclude;
import org.apache.flink.shaded.jackson2.com.fasterxml.jackson.annotation.JsonSetter;

import java.io.Serializable;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OutletDetails extends com.salescode.dim.jooq.generated.tables.pojos.OutletDetails implements Serializable {

    private List<HierarchyMetadata> immediateParent;
    private User userName;
    private Location location;

    public OutletDetails(com.salescode.dim.jooq.generated.tables.pojos.OutletDetails outletDetails) {
        super(outletDetails);
    }

    public static OutletDetails of(com.salescode.dim.jooq.generated.tables.pojos.OutletDetails outletDetails) {
        return new OutletDetails(outletDetails);
    }

    @JsonSetter("outletCode")
    public void setOutletCode(String outletCode) {
        setOutletcode(outletCode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString());
        sb.deleteCharAt(sb.length() - 1);
        sb.append(", ").append(immediateParent);
        sb.append(", ").append(userName);
        sb.append(", ").append(location);
        sb.append(")");
        return sb.toString();
    }

}
