/*
 * This file is generated by jOOQ.
 */
package com.salescode.dim.jooq.impl;


import com.applicate.services.channelkart.models.enums.ActiveStatus;
import lombok.Getter;
import lombok.Setter;
import org.apache.flink.shaded.jackson2.com.fasterxml.jackson.annotation.JsonInclude;
import org.apache.flink.shaded.jackson2.com.fasterxml.jackson.annotation.JsonSetter;

import java.io.Serializable;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OutletDetails extends com.salescode.dim.jooq.generated.tables.pojos.OutletDetails implements Serializable {

    private List<HierarchyMetadata> immediateParent;
    private User userName;
    private Location location;

    public OutletDetails(){
     super();
    }

    public OutletDetails(com.salescode.dim.jooq.generated.tables.pojos.OutletDetails outletDetails) {
        super(outletDetails);
    }

    public static OutletDetails of(com.salescode.dim.jooq.generated.tables.pojos.OutletDetails outletDetails) {
        if(outletDetails == null) {
            return null;
        }
        return new OutletDetails(outletDetails);
    }

    public User getUserName() {
        return this.userName;
    }

    public void setUserName(User userName) {
        this.userName = userName;
    }

    @JsonSetter("outletCode")
    public void setOutletCode(String outletCode) {
        setOutletcode(outletCode);
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    //Renamed to avoid clashing with generated getLocationHierarchy() from pojo
    public Location getLocationHierarchyModel() {
        return this.getLocation();
    }

    public void setLocationHierarchyModel(Location location) {
        this.setLocation(location);
    }

    public List<HierarchyMetadata> getImmediateParent() {
        return immediateParent;
    }

    public void setImmediateParent(List<HierarchyMetadata> immediateParent) {
        this.immediateParent = immediateParent;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder(super.toString());
        sb.deleteCharAt(sb.length() - 1);
        sb.append(", ").append(immediateParent);
        sb.append(", ").append(userName);
        sb.append(", ").append(location);
        sb.append(")");
        return sb.toString();
    }

}
