# Define the active profiles, default is dev,h2 or dev,postgres depending on the environment.
spring:
  application:
    name: insights

  # Set the active profiles, default to dev,h2,debug
  profiles:
    active: postgres,dev,info,kafka  # Active profiles to be loaded together

server:
  port: 8081

---

# Configuration for 'dev' profile
spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  # Development-specific settings
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/dis_insights
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: 164.52.202.184:9092

cache:
  redisUrl: redis://localhost:6379

application:
  environment: dev

app:
  active-environments:
    - dev

file:
  progress:
    update:
      topic: file-progress-updates-test
      failure:
        topic: file-progress-updates-failed

property-service:
  token: "ckt-GQpr9LQhpd_0cHJcKoVBDGT8Hu8Bbflu-ikLN87wvC0GvxGOv-bO7clbBO3RvnEPn_aibcCzdnxAECr8aftngUJE0rMXQosirYoBvdcaUv3idG_lZ8je_npgg-fc7PD18H-ZBawZANpryCVXGr-LiDJmC5yULsCf2Wp1TJtnDgcYe0p72KiWdGaxcCm2wUH5YjgNxVKIJ4feyt1hAr6NdUgZbESV8af8TypvpbWbz1tFvfEazL_HXEvu9aor3br8WMEQpzH9vFE-xst0G-MV3HjMsmm_eIQjOyWLNc4JT9EmrtK3AOh9ckpIo3rO-T48P4q-XR9I4ilIGDdDJNqpcOrwQqjFTDu3ai20yeQ77XFC81we4GJLG9WDrbTXZQ7vLQOM8FbC6qezdgUfc9jwzo4fpP5bDQwnivjtI5EW1USn8bd6TkLUyJJayMtdSdEgNhj9ERtJ8wnkoOrypZbKPsIADMLpsTRxmOe48esK1uDMLSCCO62C6yd2szCp9YlpD4p8iQG4mRCpl2ZhllNEqKS6DfV0aF2pxJaFNdIawS7hIhtDevGZN9oWlrF6IzpE5Xls_sZvoni1e42m2wE5QQMRS_sKusit8eSM7f_ZN6mORP6KCPzH0gh3OYI0Of45lbVZF5wQbvUV89X1lXbOJFModGX8Yuwnvsc97Fri80zCo2cp9f2mfaxNSk8KSUvR5bAB9SwPxxV3pyqrgxwWYUgRArymO_8-ydj7DYtSmMlsDEpmpo-zrUDGXU_2jRnb6c4MrntfLBxN9cNWDaGYUpZmZIlKQpYT6DD9_ek7acPwxBA_YrZ4TL7A4sHzR4RnteapFb0W3ytUxK-3X782hQEPron9pOzb2IuvtLAIMudAoLj5pPKuDxdvA7jdHDV92xkQvVNO8wkG1nxmGgBZRvM-rV0ChXBOmlMK53ACrCiRICog_fmitRmOU3xcT3tBkC3RM2hC-xU5jcnyk4rr_tZHw_zVGHvRDW9eJNS8aiRgcW6ZJ_sOPD-x7-s3Lo463fmgQecFF5OE7Lx2NkMYXupEw4A1OWZzWO37SnGfqATVeUkJvaV1qoG8t0qWHrgTxaW-aJCy33J_r90fQBvmWC8wE2wZk7NWwfMpCZK-IaVwGoZgEvCAhaorNAirGNZtLez7s1FVpbpw-jEhJquaDuVx9pSFMw6C1xXei-Mru6Euw8qFy-_RxJyW6SPr3qiN7bbNUXfb0Jy85u-bjcmY7a14Fz6sm7aUNF6qESTjV8tvmfpyRQ15WjDRvpb9XZjTSOIiIdGzYkWD3kFFFwjqLQQin3Cljl72SV-AiY1s8TOv0tS_ue9dG6b8CLAcynWsK-CN0F0fY3GX8NN8QE1y9w=="
---

# Configuration for 'uat' profile
spring:
  config:
    activate:
      on-profile: uat

  kafka:
    bootstrap-servers: 164.52.202.184:9092

application:
  environment: uat

app:
  active-environments:
    - dev
    - uat

file:
  progress:
    update:
      topic: file-progress-updates
      failure:
        topic: file-progress-updates-failed

---

# Configuration for 'demo' profile
spring:
  config:
    activate:
      on-profile: demo


application:
  environment: demo

app:
  active-environments: demo

file:
  progress:
    update:
      topic: file-progress-updates
      failure:
        topic: file-progress-updates-failed



---

# Configuration for 'postgres' profile (PostgreSQL-specific properties for persistent DB)
spring:
  config:
    activate:
      on-profile: postgres

  # PostgreSQL Database-specific properties for persistent database
#  jpa:
#    # Dialect for PostgreSQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

# Configuration for 'info' profile (INFO-level logging)
spring:
  config:
    activate:
      on-profile: info

# Logging level for INFO
logging:
  level:
    com.salescode: INFO
    org.springframework: INFO   # Set Spring framework logs to INFO level
    org.hibernate.SQL: INFO     # Log SQL queries at INFO level
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # Log parameter binding at INFO level
    org.springframework.web: INFO  # Set web-related logs to INFO level

---

# Configuration for 'debug' profile (DEBUG-level logging)
spring:
  config:
    activate:
      on-profile: debug

  jpa:
    show-sql: true     
    properties:
      hibernate.format_sql: true

# Logging level for DEBUG
logging:
  level:
    com.salescode: DEBUG
    org.springframework: DEBUG  # Set Spring framework logs to DEBUG level
    org.hibernate.SQL: DEBUG    # Log SQL queries at DEBUG level
    org.hibernate.type: TRACE   # Trace parameter binding for SQL
    org.hibernate.orm.jdbc.bind: TRACE # Trace parameter binding for SQL hibernate
    org.hibernate.orm.jdbc.extract: TRACE # Trace result binding for SQL hibernate
    org.springframework.web: DEBUG  # Set web-related logs to DEBUG level
    org.springframework.transaction: DEBUG
    org.springframework.kafka.core: DEBUG

---

# Configuration for 'kafka' profile

spring:
  config:
    activate:
      on-profile: kafka

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
    consumer:
      properties:
        spring.json.trusted.packages: com.salescode.dis.insights.dto.event
        spring.json.value.default.type: com.salescode.dis.insights.dto.event.FileProgressEvent
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer



