# Define the active profiles, default is dev,h2 or dev,postgres depending on the environment.
spring:
  application:
    name: insights

  # Set the active profiles, default to dev,h2,debug
  profiles:
    active: postgres,dev,info,kafka  # Active profiles to be loaded together

server:
  port: 8081

---

# Configuration for 'dev' profile
spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  # Development-specific settings
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/dis_insights
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  redshift:
    jdbc-url: jdbc:redshift://redshift-channelkart-demo.c4ncoki1rp70.ap-south-1.redshift.amazonaws.com:5439/channelkartdemo?currentSchema=ex_schema_dataintegration
    username: dataintegrationuser
    password: htZFTaQH;3lK]_
    driver-class-name: com.amazon.redshift.jdbc42.Driver

  kafka:
    bootstrap-servers: localhost:9092

  aws:
    region: ap-south-1
    s3:
      bucket-name: globalintegration

cache:
  redisUrl: redis://localhost:6379

application:
  environment: dev

app:
  active-environments:
    - dev

file:
  progress:
    update:
      topic: file-progress-updates
      failure:
        topic: file-progress-updates-failed

insights:
  order:
    topic: order-progress-updates
    group-id: order-progress-processor

property-service:
  token: "your-token-here"
---

# Configuration for 'uat' profile
spring:
  config:
    activate:
      on-profile: uat

  kafka:
    bootstrap-servers: 164.52.202.184:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  aws:
    region: ap-south-1
    s3:
      bucket-name: globalintegration


application:
  environment: uat

app:
  active-environments:
    - dev
    - uat

aws:
  region: ap-south-1
  s3:
    bucket-name: globalintegration
  aws:
    region: ap-south-1
    s3:
      bucket-name: globalintegration

file:
  progress:
    update:
      topic: file-progress-updates
      failure:
        topic: file-progress-updates-failed
insights:
  order:
    topic: order-progress-updates
    group-id: order-progress-processor

---

# Configuration for 'demo' profile
spring:
  config:
    activate:
      on-profile: demo


application:
  environment: demo

app:
  active-environments:
    - demo
    - prod

file:
  progress:
    update:
      topic: file-progress-updates
      failure:
        topic: file-progress-updates-failed

insights:
  order:
    topic: order-progress-updates
    group-id: order-progress-processor
---

# Configuration for 'postgres' profile (PostgreSQL-specific properties for persistent DB)
spring:
  config:
    activate:
      on-profile: postgres

  # PostgreSQL Database-specific properties for persistent database
#  jpa:
#    # Dialect for PostgreSQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

# Configuration for 'info' profile (INFO-level logging)
spring:
  config:
    activate:
      on-profile: info

# Logging level for INFO
logging:
  level:
    com.salescode: INFO
    org.springframework: INFO   # Set Spring framework logs to INFO level
    org.hibernate.SQL: INFO     # Log SQL queries at INFO level
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # Log parameter binding at INFO level
    org.springframework.web: INFO  # Set web-related logs to INFO level

---

# Configuration for 'debug' profile (DEBUG-level logging)
spring:
  config:
    activate:
      on-profile: debug

  jpa:
    show-sql: true     
    properties:
      hibernate.format_sql: true

# Logging level for DEBUG
logging:
  level:
    com.salescode: DEBUG
    org.springframework: DEBUG  # Set Spring framework logs to DEBUG level
    org.hibernate.SQL: DEBUG    # Log SQL queries at DEBUG level
    org.hibernate.type: TRACE   # Trace parameter binding for SQL
    org.hibernate.orm.jdbc.bind: TRACE # Trace parameter binding for SQL hibernate
    org.hibernate.orm.jdbc.extract: TRACE # Trace result binding for SQL hibernate
    org.springframework.web: DEBUG  # Set web-related logs to DEBUG level
    org.springframework.transaction: DEBUG
    org.springframework.kafka.core: DEBUG

---

# Configuration for 'kafka' profile

spring:
  config:
    activate:
      on-profile: kafka

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
    consumer:
      properties:
        spring.json.trusted.packages: com.salescode.dis.insights.dto.event
        spring.json.value.default.type: com.salescode.dis.insights.dto.event.FileProgressEvent
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    metrics:
      cache-expiry-seconds: 2
      broadcast-interval: 3000

---

# observability profile
spring:
  config:
    activate:
      on-profile: observability

salescode:
  observability:
    enabled: true
    default-protocol: http
    global-endpoint: https://pulse.salescode.ai/api/uat
    global-headers:
      authorization: Basic YWRtaW5Ac2FsZXNjb2RlLmFpOlJ1MG1sOHZ4bzNTZlQxV0k=
      stream-name: ${spring.application.name}
    default-metrics-interval: 30
    http-metrics:
      enabled: true

---

# observability-prod profile
spring:
  config:
    activate:
      on-profile: observability-prod

salescode:
  observability:
    enabled: true
    default-protocol: http
    global-endpoint: https://trace.salescode.ai/api/prod
    global-headers:
      authorization: Basic YWRtaW5Ac2FsZXNjb2RlLmFpOmF1NmN3SThlTUZoUEVmNUg=
      stream-name: ${spring.application.name}
    default-metrics-interval: 30
    http-metrics:
      enabled: true
sse:
  cleanup:
    initial-delay: 1   # minutes
    interval: 5        # minutes
